// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Keyword = 1,
  text1 = 14,
  text2 = 15,
  text3 = 16,
  JourneyDiagram = 2,
  DiagramName = 3,
  LineComment = 4,
  Text = 5,
  Task = 6,
  TaskName = 7,
  Score = 8,
  Actor = 9
