// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * CancelFunc 取消订阅函数
 * 调用此函数可以取消对配置的监听
 */
export type CancelFunc = any;

/**
 * ObserverCallback 观察者回调函数
 */
export type ObserverCallback = any;
