/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlockLanguageSelector: typeof import('./src/components/toolbar/BlockLanguageSelector.vue')['default']
    DocumentSelector: typeof import('./src/components/toolbar/DocumentSelector.vue')['default']
    LinuxTitleBar: typeof import('./src/components/titlebar/LinuxTitleBar.vue')['default']
    MacOSTitleBar: typeof import('./src/components/titlebar/MacOSTitleBar.vue')['default']
    MemoryMonitor: typeof import('./src/components/monitor/MemoryMonitor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toolbar: typeof import('./src/components/toolbar/Toolbar.vue')['default']
    WindowsTitleBar: typeof import('./src/components/titlebar/WindowsTitleBar.vue')['default']
    WindowTitleBar: typeof import('./src/components/titlebar/WindowTitleBar.vue')['default']
  }
}
