// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as theme$0 from "./theme/models.js";

/**
 * Document is the model entity for the Document schema.
 */
export class Document {
    /**
     * ID of the ent.
     */
    "id"?: number;

    /**
     * UUID for cross-device sync (UUIDv7)
     */
    "uuid": string;

    /**
     * creation time
     */
    "created_at": string;

    /**
     * update time
     */
    "updated_at": string;

    /**
     * deleted at
     */
    "deleted_at"?: string | null;

    /**
     * document title
     */
    "title": string;

    /**
     * document content
     */
    "content": string;

    /**
     * document locked status
     */
    "locked": boolean;

    /** Creates a new Document instance. */
    constructor($$source: Partial<Document> = {}) {
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("locked" in $$source)) {
            this["locked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Document instance from a string or object.
     */
    static createFrom($$source: any = {}): Document {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Document($$parsedSource as Partial<Document>);
    }
}

/**
 * Extension is the model entity for the Extension schema.
 */
export class Extension {
    /**
     * ID of the ent.
     */
    "id"?: number;

    /**
     * UUID for cross-device sync (UUIDv7)
     */
    "uuid": string;

    /**
     * creation time
     */
    "created_at": string;

    /**
     * update time
     */
    "updated_at": string;

    /**
     * deleted at
     */
    "deleted_at"?: string | null;

    /**
     * extension key
     */
    "key": string;

    /**
     * extension enabled or not
     */
    "enabled": boolean;

    /**
     * extension config
     */
    "config": { [_: string]: any };

    /** Creates a new Extension instance. */
    constructor($$source: Partial<Extension> = {}) {
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("config" in $$source)) {
            this["config"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Extension instance from a string or object.
     */
    static createFrom($$source: any = {}): Extension {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField7_0($$parsedSource["config"]);
        }
        return new Extension($$parsedSource as Partial<Extension>);
    }
}

/**
 * KeyBinding is the model entity for the KeyBinding schema.
 */
export class KeyBinding {
    /**
     * ID of the ent.
     */
    "id"?: number;

    /**
     * UUID for cross-device sync (UUIDv7)
     */
    "uuid": string;

    /**
     * creation time
     */
    "created_at": string;

    /**
     * update time
     */
    "updated_at": string;

    /**
     * deleted at
     */
    "deleted_at"?: string | null;

    /**
     * key binding key
     */
    "key": string;

    /**
     * key binding command
     */
    "command": string;

    /**
     * key binding extension
     */
    "extension"?: string;

    /**
     * key binding enabled
     */
    "enabled": boolean;

    /** Creates a new KeyBinding instance. */
    constructor($$source: Partial<KeyBinding> = {}) {
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyBinding instance from a string or object.
     */
    static createFrom($$source: any = {}): KeyBinding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyBinding($$parsedSource as Partial<KeyBinding>);
    }
}

/**
 * Theme is the model entity for the Theme schema.
 */
export class Theme {
    /**
     * ID of the ent.
     */
    "id"?: number;

    /**
     * UUID for cross-device sync (UUIDv7)
     */
    "uuid": string;

    /**
     * creation time
     */
    "created_at": string;

    /**
     * update time
     */
    "updated_at": string;

    /**
     * deleted at
     */
    "deleted_at"?: string | null;

    /**
     * theme key
     */
    "key": string;

    /**
     * theme type
     */
    "type": theme$0.Type;

    /**
     * theme colors
     */
    "colors": { [_: string]: any };

    /** Creates a new Theme instance. */
    constructor($$source: Partial<Theme> = {}) {
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ("" as theme$0.Type);
        }
        if (!("colors" in $$source)) {
            this["colors"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Theme instance from a string or object.
     */
    static createFrom($$source: any = {}): Theme {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("colors" in $$parsedSource) {
            $$parsedSource["colors"] = $$createField7_0($$parsedSource["colors"]);
        }
        return new Theme($$parsedSource as Partial<Theme>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
