// Code generated by ent, DO NOT EDIT.

package keybinding

import (
	"voidraft/internal/models/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLTE(FieldID, id))
}

// UUID applies equality check predicate on the "uuid" field. It's identical to UUIDEQ.
func UUID(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldUUID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldName, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldType, v))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldKey, v))
}

// Macos applies equality check predicate on the "macos" field. It's identical to MacosEQ.
func Macos(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldMacos, v))
}

// Windows applies equality check predicate on the "windows" field. It's identical to WindowsEQ.
func Windows(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldWindows, v))
}

// Linux applies equality check predicate on the "linux" field. It's identical to LinuxEQ.
func Linux(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldLinux, v))
}

// Extension applies equality check predicate on the "extension" field. It's identical to ExtensionEQ.
func Extension(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldExtension, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldEnabled, v))
}

// PreventDefault applies equality check predicate on the "prevent_default" field. It's identical to PreventDefaultEQ.
func PreventDefault(v bool) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldPreventDefault, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldScope, v))
}

// UUIDEQ applies the EQ predicate on the "uuid" field.
func UUIDEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldUUID, v))
}

// UUIDNEQ applies the NEQ predicate on the "uuid" field.
func UUIDNEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNEQ(FieldUUID, v))
}

// UUIDIn applies the In predicate on the "uuid" field.
func UUIDIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldIn(FieldUUID, vs...))
}

// UUIDNotIn applies the NotIn predicate on the "uuid" field.
func UUIDNotIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNotIn(FieldUUID, vs...))
}

// UUIDGT applies the GT predicate on the "uuid" field.
func UUIDGT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGT(FieldUUID, v))
}

// UUIDGTE applies the GTE predicate on the "uuid" field.
func UUIDGTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGTE(FieldUUID, v))
}

// UUIDLT applies the LT predicate on the "uuid" field.
func UUIDLT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLT(FieldUUID, v))
}

// UUIDLTE applies the LTE predicate on the "uuid" field.
func UUIDLTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLTE(FieldUUID, v))
}

// UUIDContains applies the Contains predicate on the "uuid" field.
func UUIDContains(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContains(FieldUUID, v))
}

// UUIDHasPrefix applies the HasPrefix predicate on the "uuid" field.
func UUIDHasPrefix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasPrefix(FieldUUID, v))
}

// UUIDHasSuffix applies the HasSuffix predicate on the "uuid" field.
func UUIDHasSuffix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasSuffix(FieldUUID, v))
}

// UUIDEqualFold applies the EqualFold predicate on the "uuid" field.
func UUIDEqualFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEqualFold(FieldUUID, v))
}

// UUIDContainsFold applies the ContainsFold predicate on the "uuid" field.
func UUIDContainsFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContainsFold(FieldUUID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtContains applies the Contains predicate on the "created_at" field.
func CreatedAtContains(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContains(FieldCreatedAt, v))
}

// CreatedAtHasPrefix applies the HasPrefix predicate on the "created_at" field.
func CreatedAtHasPrefix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasPrefix(FieldCreatedAt, v))
}

// CreatedAtHasSuffix applies the HasSuffix predicate on the "created_at" field.
func CreatedAtHasSuffix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasSuffix(FieldCreatedAt, v))
}

// CreatedAtEqualFold applies the EqualFold predicate on the "created_at" field.
func CreatedAtEqualFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEqualFold(FieldCreatedAt, v))
}

// CreatedAtContainsFold applies the ContainsFold predicate on the "created_at" field.
func CreatedAtContainsFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContainsFold(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtContains applies the Contains predicate on the "updated_at" field.
func UpdatedAtContains(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContains(FieldUpdatedAt, v))
}

// UpdatedAtHasPrefix applies the HasPrefix predicate on the "updated_at" field.
func UpdatedAtHasPrefix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasPrefix(FieldUpdatedAt, v))
}

// UpdatedAtHasSuffix applies the HasSuffix predicate on the "updated_at" field.
func UpdatedAtHasSuffix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasSuffix(FieldUpdatedAt, v))
}

// UpdatedAtEqualFold applies the EqualFold predicate on the "updated_at" field.
func UpdatedAtEqualFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEqualFold(FieldUpdatedAt, v))
}

// UpdatedAtContainsFold applies the ContainsFold predicate on the "updated_at" field.
func UpdatedAtContainsFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContainsFold(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtContains applies the Contains predicate on the "deleted_at" field.
func DeletedAtContains(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContains(FieldDeletedAt, v))
}

// DeletedAtHasPrefix applies the HasPrefix predicate on the "deleted_at" field.
func DeletedAtHasPrefix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasPrefix(FieldDeletedAt, v))
}

// DeletedAtHasSuffix applies the HasSuffix predicate on the "deleted_at" field.
func DeletedAtHasSuffix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasSuffix(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNotNull(FieldDeletedAt))
}

// DeletedAtEqualFold applies the EqualFold predicate on the "deleted_at" field.
func DeletedAtEqualFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEqualFold(FieldDeletedAt, v))
}

// DeletedAtContainsFold applies the ContainsFold predicate on the "deleted_at" field.
func DeletedAtContainsFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContainsFold(FieldDeletedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContainsFold(FieldType, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasSuffix(FieldKey, v))
}

// KeyIsNil applies the IsNil predicate on the "key" field.
func KeyIsNil() predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldIsNull(FieldKey))
}

// KeyNotNil applies the NotNil predicate on the "key" field.
func KeyNotNil() predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNotNull(FieldKey))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContainsFold(FieldKey, v))
}

// MacosEQ applies the EQ predicate on the "macos" field.
func MacosEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldMacos, v))
}

// MacosNEQ applies the NEQ predicate on the "macos" field.
func MacosNEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNEQ(FieldMacos, v))
}

// MacosIn applies the In predicate on the "macos" field.
func MacosIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldIn(FieldMacos, vs...))
}

// MacosNotIn applies the NotIn predicate on the "macos" field.
func MacosNotIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNotIn(FieldMacos, vs...))
}

// MacosGT applies the GT predicate on the "macos" field.
func MacosGT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGT(FieldMacos, v))
}

// MacosGTE applies the GTE predicate on the "macos" field.
func MacosGTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGTE(FieldMacos, v))
}

// MacosLT applies the LT predicate on the "macos" field.
func MacosLT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLT(FieldMacos, v))
}

// MacosLTE applies the LTE predicate on the "macos" field.
func MacosLTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLTE(FieldMacos, v))
}

// MacosContains applies the Contains predicate on the "macos" field.
func MacosContains(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContains(FieldMacos, v))
}

// MacosHasPrefix applies the HasPrefix predicate on the "macos" field.
func MacosHasPrefix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasPrefix(FieldMacos, v))
}

// MacosHasSuffix applies the HasSuffix predicate on the "macos" field.
func MacosHasSuffix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasSuffix(FieldMacos, v))
}

// MacosIsNil applies the IsNil predicate on the "macos" field.
func MacosIsNil() predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldIsNull(FieldMacos))
}

// MacosNotNil applies the NotNil predicate on the "macos" field.
func MacosNotNil() predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNotNull(FieldMacos))
}

// MacosEqualFold applies the EqualFold predicate on the "macos" field.
func MacosEqualFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEqualFold(FieldMacos, v))
}

// MacosContainsFold applies the ContainsFold predicate on the "macos" field.
func MacosContainsFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContainsFold(FieldMacos, v))
}

// WindowsEQ applies the EQ predicate on the "windows" field.
func WindowsEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldWindows, v))
}

// WindowsNEQ applies the NEQ predicate on the "windows" field.
func WindowsNEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNEQ(FieldWindows, v))
}

// WindowsIn applies the In predicate on the "windows" field.
func WindowsIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldIn(FieldWindows, vs...))
}

// WindowsNotIn applies the NotIn predicate on the "windows" field.
func WindowsNotIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNotIn(FieldWindows, vs...))
}

// WindowsGT applies the GT predicate on the "windows" field.
func WindowsGT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGT(FieldWindows, v))
}

// WindowsGTE applies the GTE predicate on the "windows" field.
func WindowsGTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGTE(FieldWindows, v))
}

// WindowsLT applies the LT predicate on the "windows" field.
func WindowsLT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLT(FieldWindows, v))
}

// WindowsLTE applies the LTE predicate on the "windows" field.
func WindowsLTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLTE(FieldWindows, v))
}

// WindowsContains applies the Contains predicate on the "windows" field.
func WindowsContains(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContains(FieldWindows, v))
}

// WindowsHasPrefix applies the HasPrefix predicate on the "windows" field.
func WindowsHasPrefix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasPrefix(FieldWindows, v))
}

// WindowsHasSuffix applies the HasSuffix predicate on the "windows" field.
func WindowsHasSuffix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasSuffix(FieldWindows, v))
}

// WindowsIsNil applies the IsNil predicate on the "windows" field.
func WindowsIsNil() predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldIsNull(FieldWindows))
}

// WindowsNotNil applies the NotNil predicate on the "windows" field.
func WindowsNotNil() predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNotNull(FieldWindows))
}

// WindowsEqualFold applies the EqualFold predicate on the "windows" field.
func WindowsEqualFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEqualFold(FieldWindows, v))
}

// WindowsContainsFold applies the ContainsFold predicate on the "windows" field.
func WindowsContainsFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContainsFold(FieldWindows, v))
}

// LinuxEQ applies the EQ predicate on the "linux" field.
func LinuxEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldLinux, v))
}

// LinuxNEQ applies the NEQ predicate on the "linux" field.
func LinuxNEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNEQ(FieldLinux, v))
}

// LinuxIn applies the In predicate on the "linux" field.
func LinuxIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldIn(FieldLinux, vs...))
}

// LinuxNotIn applies the NotIn predicate on the "linux" field.
func LinuxNotIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNotIn(FieldLinux, vs...))
}

// LinuxGT applies the GT predicate on the "linux" field.
func LinuxGT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGT(FieldLinux, v))
}

// LinuxGTE applies the GTE predicate on the "linux" field.
func LinuxGTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGTE(FieldLinux, v))
}

// LinuxLT applies the LT predicate on the "linux" field.
func LinuxLT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLT(FieldLinux, v))
}

// LinuxLTE applies the LTE predicate on the "linux" field.
func LinuxLTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLTE(FieldLinux, v))
}

// LinuxContains applies the Contains predicate on the "linux" field.
func LinuxContains(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContains(FieldLinux, v))
}

// LinuxHasPrefix applies the HasPrefix predicate on the "linux" field.
func LinuxHasPrefix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasPrefix(FieldLinux, v))
}

// LinuxHasSuffix applies the HasSuffix predicate on the "linux" field.
func LinuxHasSuffix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasSuffix(FieldLinux, v))
}

// LinuxIsNil applies the IsNil predicate on the "linux" field.
func LinuxIsNil() predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldIsNull(FieldLinux))
}

// LinuxNotNil applies the NotNil predicate on the "linux" field.
func LinuxNotNil() predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNotNull(FieldLinux))
}

// LinuxEqualFold applies the EqualFold predicate on the "linux" field.
func LinuxEqualFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEqualFold(FieldLinux, v))
}

// LinuxContainsFold applies the ContainsFold predicate on the "linux" field.
func LinuxContainsFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContainsFold(FieldLinux, v))
}

// ExtensionEQ applies the EQ predicate on the "extension" field.
func ExtensionEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldExtension, v))
}

// ExtensionNEQ applies the NEQ predicate on the "extension" field.
func ExtensionNEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNEQ(FieldExtension, v))
}

// ExtensionIn applies the In predicate on the "extension" field.
func ExtensionIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldIn(FieldExtension, vs...))
}

// ExtensionNotIn applies the NotIn predicate on the "extension" field.
func ExtensionNotIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNotIn(FieldExtension, vs...))
}

// ExtensionGT applies the GT predicate on the "extension" field.
func ExtensionGT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGT(FieldExtension, v))
}

// ExtensionGTE applies the GTE predicate on the "extension" field.
func ExtensionGTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGTE(FieldExtension, v))
}

// ExtensionLT applies the LT predicate on the "extension" field.
func ExtensionLT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLT(FieldExtension, v))
}

// ExtensionLTE applies the LTE predicate on the "extension" field.
func ExtensionLTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLTE(FieldExtension, v))
}

// ExtensionContains applies the Contains predicate on the "extension" field.
func ExtensionContains(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContains(FieldExtension, v))
}

// ExtensionHasPrefix applies the HasPrefix predicate on the "extension" field.
func ExtensionHasPrefix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasPrefix(FieldExtension, v))
}

// ExtensionHasSuffix applies the HasSuffix predicate on the "extension" field.
func ExtensionHasSuffix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasSuffix(FieldExtension, v))
}

// ExtensionEqualFold applies the EqualFold predicate on the "extension" field.
func ExtensionEqualFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEqualFold(FieldExtension, v))
}

// ExtensionContainsFold applies the ContainsFold predicate on the "extension" field.
func ExtensionContainsFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContainsFold(FieldExtension, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNEQ(FieldEnabled, v))
}

// PreventDefaultEQ applies the EQ predicate on the "prevent_default" field.
func PreventDefaultEQ(v bool) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldPreventDefault, v))
}

// PreventDefaultNEQ applies the NEQ predicate on the "prevent_default" field.
func PreventDefaultNEQ(v bool) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNEQ(FieldPreventDefault, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.KeyBinding {
	return predicate.KeyBinding(sql.FieldContainsFold(FieldScope, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.KeyBinding) predicate.KeyBinding {
	return predicate.KeyBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.KeyBinding) predicate.KeyBinding {
	return predicate.KeyBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.KeyBinding) predicate.KeyBinding {
	return predicate.KeyBinding(sql.NotPredicates(p))
}
