// Code generated by ent, DO NOT EDIT.

package syncrunlog

import (
	"voidraft/internal/models/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldLTE(FieldID, id))
}

// TargetPath applies equality check predicate on the "target_path" field. It's identical to TargetPathEQ.
func TargetPath(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldEQ(FieldTargetPath, v))
}

// Branch applies equality check predicate on the "branch" field. It's identical to BranchEQ.
func Branch(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldEQ(FieldBranch, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldEQ(FieldFinishedAt, v))
}

// TargetTypeEQ applies the EQ predicate on the "target_type" field.
func TargetTypeEQ(v TargetType) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldEQ(FieldTargetType, v))
}

// TargetTypeNEQ applies the NEQ predicate on the "target_type" field.
func TargetTypeNEQ(v TargetType) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldNEQ(FieldTargetType, v))
}

// TargetTypeIn applies the In predicate on the "target_type" field.
func TargetTypeIn(vs ...TargetType) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldIn(FieldTargetType, vs...))
}

// TargetTypeNotIn applies the NotIn predicate on the "target_type" field.
func TargetTypeNotIn(vs ...TargetType) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldNotIn(FieldTargetType, vs...))
}

// TargetPathEQ applies the EQ predicate on the "target_path" field.
func TargetPathEQ(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldEQ(FieldTargetPath, v))
}

// TargetPathNEQ applies the NEQ predicate on the "target_path" field.
func TargetPathNEQ(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldNEQ(FieldTargetPath, v))
}

// TargetPathIn applies the In predicate on the "target_path" field.
func TargetPathIn(vs ...string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldIn(FieldTargetPath, vs...))
}

// TargetPathNotIn applies the NotIn predicate on the "target_path" field.
func TargetPathNotIn(vs ...string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldNotIn(FieldTargetPath, vs...))
}

// TargetPathGT applies the GT predicate on the "target_path" field.
func TargetPathGT(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldGT(FieldTargetPath, v))
}

// TargetPathGTE applies the GTE predicate on the "target_path" field.
func TargetPathGTE(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldGTE(FieldTargetPath, v))
}

// TargetPathLT applies the LT predicate on the "target_path" field.
func TargetPathLT(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldLT(FieldTargetPath, v))
}

// TargetPathLTE applies the LTE predicate on the "target_path" field.
func TargetPathLTE(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldLTE(FieldTargetPath, v))
}

// TargetPathContains applies the Contains predicate on the "target_path" field.
func TargetPathContains(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldContains(FieldTargetPath, v))
}

// TargetPathHasPrefix applies the HasPrefix predicate on the "target_path" field.
func TargetPathHasPrefix(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldHasPrefix(FieldTargetPath, v))
}

// TargetPathHasSuffix applies the HasSuffix predicate on the "target_path" field.
func TargetPathHasSuffix(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldHasSuffix(FieldTargetPath, v))
}

// TargetPathEqualFold applies the EqualFold predicate on the "target_path" field.
func TargetPathEqualFold(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldEqualFold(FieldTargetPath, v))
}

// TargetPathContainsFold applies the ContainsFold predicate on the "target_path" field.
func TargetPathContainsFold(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldContainsFold(FieldTargetPath, v))
}

// BranchEQ applies the EQ predicate on the "branch" field.
func BranchEQ(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldEQ(FieldBranch, v))
}

// BranchNEQ applies the NEQ predicate on the "branch" field.
func BranchNEQ(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldNEQ(FieldBranch, v))
}

// BranchIn applies the In predicate on the "branch" field.
func BranchIn(vs ...string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldIn(FieldBranch, vs...))
}

// BranchNotIn applies the NotIn predicate on the "branch" field.
func BranchNotIn(vs ...string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldNotIn(FieldBranch, vs...))
}

// BranchGT applies the GT predicate on the "branch" field.
func BranchGT(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldGT(FieldBranch, v))
}

// BranchGTE applies the GTE predicate on the "branch" field.
func BranchGTE(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldGTE(FieldBranch, v))
}

// BranchLT applies the LT predicate on the "branch" field.
func BranchLT(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldLT(FieldBranch, v))
}

// BranchLTE applies the LTE predicate on the "branch" field.
func BranchLTE(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldLTE(FieldBranch, v))
}

// BranchContains applies the Contains predicate on the "branch" field.
func BranchContains(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldContains(FieldBranch, v))
}

// BranchHasPrefix applies the HasPrefix predicate on the "branch" field.
func BranchHasPrefix(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldHasPrefix(FieldBranch, v))
}

// BranchHasSuffix applies the HasSuffix predicate on the "branch" field.
func BranchHasSuffix(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldHasSuffix(FieldBranch, v))
}

// BranchEqualFold applies the EqualFold predicate on the "branch" field.
func BranchEqualFold(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldEqualFold(FieldBranch, v))
}

// BranchContainsFold applies the ContainsFold predicate on the "branch" field.
func BranchContainsFold(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldContainsFold(FieldBranch, v))
}

// TriggerTypeEQ applies the EQ predicate on the "trigger_type" field.
func TriggerTypeEQ(v TriggerType) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldEQ(FieldTriggerType, v))
}

// TriggerTypeNEQ applies the NEQ predicate on the "trigger_type" field.
func TriggerTypeNEQ(v TriggerType) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldNEQ(FieldTriggerType, v))
}

// TriggerTypeIn applies the In predicate on the "trigger_type" field.
func TriggerTypeIn(vs ...TriggerType) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldIn(FieldTriggerType, vs...))
}

// TriggerTypeNotIn applies the NotIn predicate on the "trigger_type" field.
func TriggerTypeNotIn(vs ...TriggerType) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldNotIn(FieldTriggerType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldNotIn(FieldStatus, vs...))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtContains applies the Contains predicate on the "started_at" field.
func StartedAtContains(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldContains(FieldStartedAt, v))
}

// StartedAtHasPrefix applies the HasPrefix predicate on the "started_at" field.
func StartedAtHasPrefix(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldHasPrefix(FieldStartedAt, v))
}

// StartedAtHasSuffix applies the HasSuffix predicate on the "started_at" field.
func StartedAtHasSuffix(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldHasSuffix(FieldStartedAt, v))
}

// StartedAtEqualFold applies the EqualFold predicate on the "started_at" field.
func StartedAtEqualFold(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldEqualFold(FieldStartedAt, v))
}

// StartedAtContainsFold applies the ContainsFold predicate on the "started_at" field.
func StartedAtContainsFold(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldContainsFold(FieldStartedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtContains applies the Contains predicate on the "finished_at" field.
func FinishedAtContains(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldContains(FieldFinishedAt, v))
}

// FinishedAtHasPrefix applies the HasPrefix predicate on the "finished_at" field.
func FinishedAtHasPrefix(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldHasPrefix(FieldFinishedAt, v))
}

// FinishedAtHasSuffix applies the HasSuffix predicate on the "finished_at" field.
func FinishedAtHasSuffix(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldHasSuffix(FieldFinishedAt, v))
}

// FinishedAtEqualFold applies the EqualFold predicate on the "finished_at" field.
func FinishedAtEqualFold(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldEqualFold(FieldFinishedAt, v))
}

// FinishedAtContainsFold applies the ContainsFold predicate on the "finished_at" field.
func FinishedAtContainsFold(v string) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.FieldContainsFold(FieldFinishedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SyncRunLog) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SyncRunLog) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SyncRunLog) predicate.SyncRunLog {
	return predicate.SyncRunLog(sql.NotPredicates(p))
}
