// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {blockContent} from "./external-tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!|QQOQOOOVOQO'#C`O$OOPO'#C_OOOO'#Cf'#CfQQOQOOOOOO'#Ca'#CaO$TOSO,58zOOOO,58y,58yOOOO-E6d-E6dOOOO'#Cb'#CbOOOO'#Cg'#CgO$cOSO1G.fOOOP1G.f1G.fOOOO-E6e-E6eOOOP7+$Q7+$Q",
  stateData: "$q~O]PO~O^TO_TO`TOaTObTOcTOdTOeTOfTOgTOhTOiTOjTOkTOlTOmTOnTOoTOpTOqTOrTOsTOtTOuTOvTOwTOxTOyTOzTO{TO|TO}TO!OTO!PTO!QTO!RTO!STO!TTO!UTO!VTO!WTO!XTO!YTO~OPVO~OVXOWXOXXO!Z[O~OVXOWXOXXO!Z^O~O",
  goto: "x[PPP]aehPPPlrTROSTQOSRUPTYUZQSORWSQZUR]Z",
  nodeNames: "⚠ BlockContent Document Block BlockDelimiter BlockLanguage BlockFlag Auto ReadOnly Writable",
  maxTerm: 57,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "5o~ReYZ!d}!O!}#T#U#j#V#W$e#W#X%f#X#Y'X#Z#['r#[#](o#]#^)f#^#_*T#_#`+S#`#a+_#a#b-[#d#e.s#f#g/l#g#h0P#h#i2v#j#k3{#k#l4^#l#m4u#m#n5WR!iP!ZQ%&x%&y!lP!oP%&x%&y!rP!uP%&x%&y!xP!}O]P~#QR#T#U#Z#f#g#`#k#l#e~#`OV~~#eOW~~#jOX~~#mP#b#c#p~#sP#Z#[#v~#yP#i#j#|~$PP#`#a$S~$VP#T#U$Y~$]P#f#g$`~$eO!U~~$hR#`#a$q#d#e$|#g#h%X~$tP#^#_$w~$|Op~~%PP#d#e%S~%XOh~~%^Pj~#g#h%a~%fOf~~%iQ#T#U%o#c#d&Q~%rP#f#g%u~%xP#h#i%{~&QOy~~&TP#V#W&W~&ZP#_#`&^~&aP#X#Y&d~&gP#f#g&j~&mP#Y#Z&p~&sP#]#^&v~&yP#`#a&|~'PP#X#Y'S~'XO|~~'[Q#f#g'b#l#m'm~'eP#`#a'h~'mOr~~'rOq~~'uQ#c#d'{#f#g(Q~(QOo~~(TP#c#d(W~(ZP#c#d(^~(aP#j#k(d~(gP#m#n(j~(oOw~~(rP#h#i(u~(xQ#a#b)O#h#i)Z~)RP#`#a)U~)ZOa~~)^P#d#e)a~)fO!W~~)iP#a#b)l~)oP#T#U)r~)uP#Z#[)x~){P#X#Y*O~*TO!Y~~*WQ#T#U*^#g#h*o~*aP#j#k*d~*gP#T#U*j~*oOd~~*tPs~#c#d*w~*zP#b#c*}~+SO_~~+VP#h#i+Y~+_Ov~~+bR#X#Y+k#]#^,b#i#j-P~+nQ#g#h+t#n#o,P~+wP#g#h+z~,PO!T~~,SP#X#Y,V~,YP#f#g,]~,bO!P~~,eP#e#f,h~,kP#i#j,n~,qP#]#^,t~,wP#W#X,z~-PO!Q~~-SP#T#U-V~-[O}~~-_R#T#U-h#W#X-y#X#Y.O~-kP#h#i-n~-qP#[#]-t~-yO{~~.OOc~~.RP#f#g.U~.XP#a#b.[~._P#T#U.b~.eP#]#^.h~.kP#W#X.n~.sO!X~~.vR#[#]/P#g#h/[#m#n/g~/SP#d#e/V~/[Oe~~/_P!R!S/b~/gOx~~/lO`~~/oQ#U#V/u#g#h/z~/zOk~~0POi~~0SU#T#U0f#V#W0w#[#]1`#e#f1e#j#k1p#k#l2_~0iP#g#h0l~0oP#g#h0r~0wO!S~~0zP#T#U0}~1QP#`#a1T~1WP#T#U1Z~1`Oz~~1eOl~~1hP#`#a1k~1pOb~~1sP#X#Y1v~1yP#`#a1|~2PP#h#i2S~2VP#X#Y2Y~2_O!V~~2bP#]#^2e~2hP#Y#Z2k~2nP#h#i2q~2vOu~~2yR#X#Y3S#c#d3e#g#h3v~3VP#l#m3Y~3]P#h#i3`~3eO^~~3hP#a#b3k~3nP#`#a3q~3vOn~~3{Ot~~4OP#i#j4R~4UP#X#Y4X~4^O!O~~4aP#T#U4d~4gP#g#h4j~4mP#h#i4p~4uO!R~~4xP#a#b4{~5OP#`#a5R~5WOg~~5ZP#T#U5^~5aP#a#b5d~5gP#`#a5j~5oOm~",
  tokenizers: [blockContent, 0, 1],
  topRules: {"Document":[0,2]},
  tokenPrec: 0
})
