// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Script = 1,
  Element = 2,
  Boolean = 3,
  Identifier = 4,
  Null = 5,
  Function = 6,
  Constant = 7,
  Unit = 8,
  Currency = 9,
  LineComment = 10,
  Number = 11,
  String = 12,
  Operator = 13,
  Punctuation = 14
