// SQL方言特征检测规则
const dialectPatterns = {
  mysql: [
    /\bAUTO_INCREMENT\b/i,
    /\bENGINE\s*=/i,
    /\bCHARSET\s*=/i,
    /\bCOLLATE\s*=/i,
    /\bLIMIT\s+\d+\s*OFFSET\s+\d+/i,
    /\bUNSIGNED\b/i,
    /\bTINYINT\b/i,
    /\bMEDIUMINT\b/i,
    /\bBIGINT\b/i,
    /\bTEXT\b/i,
    /\bLONGTEXT\b/i,
    /\bMEDIUMTEXT\b/i,
    /\bTINYTEXT\b/i,
    /\bENUM\s*\(/i,
    /\bSET\s*\(/i,
    /\bIF\s*\(/i,
    /\bIFNULL\s*\(/i,
    /\bCONCAT\s*\(/i,
    /\bGROUP_CONCAT\s*\(/i,
    /\bDATE_FORMAT\s*\(/i,
    /\bSTR_TO_DATE\s*\(/i,
    /\bUNIX_TIMESTAMP\s*\(/i,
    /\bFROM_UNIXTIME\s*\(/i,
    /\bINSERT\s+IGNORE\b/i,
    /\bREPLACE\s+INTO\b/i,
    /\bON\s+DUPLICATE\s+KEY\s+UPDATE\b/i
  ],
  
  postgresql: [
    /\bSERIAL\b/i,
    /\bBIGSERIAL\b/i,
    /\bSMALLSERIAL\b/i,
    /\bBOOLEAN\b/i,
    /\bTEXT\[\]/i,
    /\bINTEGER\[\]/i,
    /\bJSONB\b/i,
    /\bUUID\b/i,
    /\bINET\b/i,
    /\bCIDR\b/i,
    /\bMACaddr\b/i,
    /\bTSVECTOR\b/i,
    /\bTSQUERY\b/i,
    /\bPOINT\b/i,
    /\bLINE\b/i,
    /\bLSEG\b/i,
    /\bBOX\b/i,
    /\bPATH\b/i,
    /\bPOLYGON\b/i,
    /\bCIRCLE\b/i,
    /\bLIMIT\s+\d+\s+OFFSET\s+\d+/i,
    /\bRETURNING\b/i,
    /\bON\s+CONFLICT\b/i,
    /\bDO\s+NOTHING\b/i,
    /\bDO\s+UPDATE\s+SET\b/i,
    /\bFETCH\s+FIRST\b/i,
    /\bFETCH\s+NEXT\b/i,
    /\bROWS\s+ONLY\b/i,
    /\bWITH\s+RECURSIVE\b/i,
    /\bARRAY\s*\[/i,
    /\bUNNEST\s*\(/i,
    /\bSTRING_AGG\s*\(/i,
    /\bEXTRACT\s*\(/i,
    /\bGENERATE_SERIES\s*\(/i,
    /\bCOALESCE\s*\(/i,
    /\bNULLIF\s*\(/i,
    /\bAGE\s*\(/i,
    /\bNOW\s*\(\s*\)/i,
    /\bCURRENT_TIMESTAMP\b/i,
    /\bCURRENT_DATE\b/i,
    /\bCURRENT_TIME\b/i,
    /\bINTERVAL\s+'/i,
    /\bREGEXP_REPLACE\s*\(/i,
    /\bREGEXP_SPLIT_TO_ARRAY\s*\(/i,
    /\b\$\$[^$]*\$\$/i,
    /\bCREATE\s+EXTENSION\b/i,
    /\bCREATE\s+OR\s+REPLACE\s+FUNCTION\b/i,
    /\bCREATE\s+OR\s+REPLACE\s+VIEW\b/i,
    /\bPLPGSQL\b/i,
    /\bTABLESPACE\b/i,
    /\bSCHEMA\b/i
  ],

  sqlite: [
    /\bPRAGMA\b/i,
    /\bAUTOINCREMENT\b/i,
    /\bWITHOUT\s+ROWID\b/i,
    /\bSTRICT\b/i,
    /\bIF\s+NOT\s+EXISTS\b/i,
    /\bREPLACE\b/i,
    /\bVACUUM\b/i,
    /\bREINDEX\b/i,
    /\bANALYZE\b/i,
    /\bATTACH\s+DATABASE\b/i,
    /\bDETACH\s+DATABASE\b/i,
    /\bTEMP\b/i,
    /\bTEMPORARY\b/i,
    /\bBEGIN\s+IMMEDIATE\b/i,
    /\bBEGIN\s+EXCLUSIVE\b/i,
    /\bEXPLAIN\s+QUERY\s+PLAN\b/i,
    /\bRANDOM\s*\(\s*\)/i,
    /\bLENGTH\s*\(/i,
    /\bSUBSTR\s*\(/i,
    /\bREPLACE\s*\(/i,
    /\bTRIM\s*\(/i,
    /\bLTRIM\s*\(/i,
    /\bRTRIM\s*\(/i,
    /\bUPPER\s*\(/i,
    /\bLOWER\s*\(/i,
    /\bINSTR\s*\(/i,
    /\bROUND\s*\(/i,
    /\bABS\s*\(/i,
    /\bMAX\s*\(/i,
    /\bMIN\s*\(/i,
    /\bDATE\s*\(/i,
    /\bTIME\s*\(/i,
    /\bDATETIME\s*\(/i,
    /\bJULIANDAY\s*\(/i,
    /\bSTRFTIME\s*\(/i,
    /\bGLOB\s*\(/i,
    /\bLIKE\s*\(/i,
    /\bCAST\s*\(/i,
    /\bTYPEOF\s*\(/i
  ],

  transactsql: [
    /\bIDENTITY\s*\(/i,
    /\bUNIQUEIDENTIFIER\b/i,
    /\bNVARCHAR\b/i,
    /\bNTEXT\b/i,
    /\bNUMERIC\b/i,
    /\bSMALLDATETIME\b/i,
    /\bDATETIME2\b/i,
    /\bDATETIMEOFFSET\b/i,
    /\bTIME\b/i,
    /\bIMAGE\b/i,
    /\bMONEY\b/i,
    /\bSMALLMONEY\b/i,
    /\bSQL_VARIANT\b/i,
    /\bTABLE\b/i,
    /\bXML\b/i,
    /\bGEOMETRY\b/i,
    /\bGEOGRAPHY\b/i,
    /\bTOP\s+\d+/i,
    /\bPERCENT\b/i,
    /\bWITH\s+TIES\b/i,
    /\bOFFSET\s+\d+\s+ROWS/i,
    /\bFETCH\s+NEXT\s+\d+\s+ROWS\s+ONLY/i,
    /\bISNULL\s*\(/i,
    /\bCONVERT\s*\(/i,
    /\bCAST\s*\(/i,
    /\bDATEDIFF\s*\(/i,
    /\bDATEADD\s*\(/i,
    /\bDATEPART\s*\(/i,
    /\bGETDATE\s*\(\s*\)/i,
    /\bGETUTCDATE\s*\(\s*\)/i,
    /\bSYSDATETIME\s*\(\s*\)/i,
    /\bSYSUTCDATETIME\s*\(\s*\)/i,
    /\bCURRENT_TIMESTAMP\b/i,
    /\bLEN\s*\(/i,
    /\bLEFT\s*\(/i,
    /\bRIGHT\s*\(/i,
    /\bCHARINDEX\s*\(/i,
    /\bPATINDEX\s*\(/i,
    /\bSTUFF\s*\(/i,
    /\bREVERSE\s*\(/i,
    /\bREPLICATE\s*\(/i,
    /\bSPACE\s*\(/i,
    /\bSTR\s*\(/i,
    /\bFORMAT\s*\(/i,
    /\bPARSENAME\s*\(/i,
    /\bQUOTENAME\s*\(/i,
    /\bMERGE\b/i,
    /\bWHEN\s+MATCHED\b/i,
    /\bWHEN\s+NOT\s+MATCHED\b/i,
    /\bUSING\b/i,
    /\bOUTPUT\b/i,
    /\bINSERTED\b/i,
    /\bDELETED\b/i,
    /\bTRUNCATE\s+TABLE\b/i,
    /\bEXEC\b/i,
    /\bEXECUTE\b/i,
    /\bSP_EXECUTESQL\b/i,
    /\bBEGIN\s+TRAN\b/i,
    /\bCOMMIT\s+TRAN\b/i,
    /\bROLLBACK\s+TRAN\b/i,
    /\bSAVE\s+TRAN\b/i,
    /\bTRY\b/i,
    /\bCATCH\b/i,
    /\bTHROW\b/i,
    /\bRAISERROR\b/i,
    /\bPRINT\b/i,
    /\bSET\s+NOCOUNT\s+ON\b/i,
    /\bSET\s+ANSI_NULLS\s+ON\b/i,
    /\bSET\s+QUOTED_IDENTIFIER\s+ON\b/i,
    /\bWITH\s+\(\s*NOLOCK\s*\)/i,
    /\bROW_NUMBER\s*\(\s*\)\s+OVER\s*\(/i,
    /\bRANK\s*\(\s*\)\s+OVER\s*\(/i,
    /\bDENSE_RANK\s*\(\s*\)\s+OVER\s*\(/i,
    /\bNTILE\s*\(/i,
    /\bLAG\s*\(/i,
    /\bLEAD\s*\(/i,
    /\bFIRST_VALUE\s*\(/i,
    /\bLAST_VALUE\s*\(/i,
    /\bCTE\b/i,
    /\bPIVOT\b/i,
    /\bUNPIVOT\b/i,
    /\bAPPLY\b/i,
    /\bOUTER\s+APPLY\b/i,
    /\bCROSS\s+APPLY\b/i
  ],

  bigquery: [
    /\bSTRUCT\s*</i,
    /\bARRAY\s*</i,
    /\bWITH\s+RECURSIVE\b/i,
    /\bUNNEST\s*\(/i,
    /\bGENERATE_ARRAY\s*\(/i,
    /\bGENERATE_DATE_ARRAY\s*\(/i,
    /\bARRAY_AGG\s*\(/i,
    /\bARRAY_CONCAT\s*\(/i,
    /\bARRAY_LENGTH\s*\(/i,
    /\bSAFE_CAST\s*\(/i,
    /\bSAFE_DIVIDE\s*\(/i,
    /\bIFNULL\s*\(/i,
    /\bNULLIF\s*\(/i,
    /\bCOALESCE\s*\(/i,
    /\bDATE\s*\(/i,
    /\bTIME\s*\(/i,
    /\bDATETIME\s*\(/i,
    /\bTIMESTAMP\s*\(/i,
    /\bDATE_ADD\s*\(/i,
    /\bDATE_SUB\s*\(/i,
    /\bDATE_DIFF\s*\(/i,
    /\bDATE_TRUNC\s*\(/i,
    /\bFORMAT_DATE\s*\(/i,
    /\bPARSE_DATE\s*\(/i,
    /\bEXTRACT\s*\(/i,
    /\bCURRENT_DATE\s*\(\s*\)/i,
    /\bCURRENT_DATETIME\s*\(\s*\)/i,
    /\bCURRENT_TIME\s*\(\s*\)/i,
    /\bCURRENT_TIMESTAMP\s*\(\s*\)/i,
    /\bSTRING\s*\(/i,
    /\bBYTES\s*\(/i,
    /\bINT64\b/i,
    /\bFLOAT64\b/i,
    /\bBOOL\b/i,
    /\bGEOGRAPHY\b/i,
    /\bJSON\b/i,
    /\bNUMERIC\b/i,
    /\bBIGNUMERIC\b/i,
    /\bREGEXP_CONTAINS\s*\(/i,
    /\bREGEXP_EXTRACT\s*\(/i,
    /\bREGEXP_REPLACE\s*\(/i,
    /\bSPLIT\s*\(/i,
    /\bSTRPOS\s*\(/i,
    /\bSTRING_AGG\s*\(/i,
    /\bFARMHASH\s*\(/i,
    /\bSHA1\s*\(/i,
    /\bSHA256\s*\(/i,
    /\bSHA512\s*\(/i,
    /\bTO_BASE32\s*\(/i,
    /\bFROM_BASE32\s*\(/i,
    /\bTO_BASE64\s*\(/i,
    /\bFROM_BASE64\s*\(/i,
    /\bTO_HEX\s*\(/i,
    /\bFROM_HEX\s*\(/i,
    /\bML\.PREDICT\s*\(/i,
    /\bML\.EVALUATE\s*\(/i,
    /\bML\.TRAINING_INFO\s*\(/i,
    /\bCREATE\s+OR\s+REPLACE\s+MODEL\b/i,
    /\bCREATE\s+MODEL\b/i,
    /\bOPTIONS\s*\(/i,
    /\bPARTITION\s+BY\s+DATE\s*\(/i,
    /\bCLUSTER\s+BY\b/i,
    /\b_TABLE_SUFFIX\b/i,
    /\b_PARTITIONTIME\b/i,
    /\b_PARTITIONDATE\b/i,
    /\bQUALIFY\b/i,
    /\bEXCEPT\s*\(/i,
    /\bREPLACE\s*\(/i,
    /\bTABLESAMPLE\s+SYSTEM\s*\(/i,
    /\bUNPIVOT\s*\(/i,
    /\bPIVOT\s*\(/i,
    /\bWINDOW\b/i,
    /\bOVER\s*\(\s*PARTITION\s+BY\b/i,
    /\bLAG\s*\(/i,
    /\bLEAD\s*\(/i,
    /\bFIRST_VALUE\s*\(/i,
    /\bLAST_VALUE\s*\(/i,
    /\bNTH_VALUE\s*\(/i,
    /\bROW_NUMBER\s*\(\s*\)/i,
    /\bRANK\s*\(\s*\)/i,
    /\bDENSE_RANK\s*\(\s*\)/i,
    /\bPERCENT_RANK\s*\(\s*\)/i,
    /\bCUME_DIST\s*\(\s*\)/i,
    /\bNTILE\s*\(/i
  ],

  snowflake: [
    /\bVARIANT\b/i,
    /\bOBJECT\b/i,
    /\bARRAY\b/i,
    /\bGEOGRAPHY\b/i,
    /\bGEOMETRY\b/i,
    /\bVECTOR\b/i,
    /\bAUTOINCREMENT\b/i,
    /\bIDENTITY\s*\(/i,
    /\bCLUSTER\s+BY\s*\(/i,
    /\bCHANGE_TRACKING\s*=\s*TRUE/i,
    /\bCOPY\s+GRANTS\b/i,
    /\bTIME_TRAVEL\b/i,
    /\bAT\s*\(\s*TIMESTAMP\s*=>/i,
    /\bBEFORE\s*\(\s*TIMESTAMP\s*=>/i,
    /\bQUALIFY\b/i,
    /\bMINUS\b/i,
    /\bCONCAT\s*\(/i,
    /\bCONCAT_WS\s*\(/i,
    /\bSPLIT\s*\(/i,
    /\bSPLIT_PART\s*\(/i,
    /\bSTARTSWITH\s*\(/i,
    /\bENDSWITH\s*\(/i,
    /\bCONTAINS\s*\(/i,
    /\bTRY_CAST\s*\(/i,
    /\bTRY_TO_NUMBER\s*\(/i,
    /\bTRY_TO_DECIMAL\s*\(/i,
    /\bTRY_TO_DATE\s*\(/i,
    /\bTRY_TO_TIME\s*\(/i,
    /\bTRY_TO_TIMESTAMP\s*\(/i,
    /\bTRY_TO_BINARY\s*\(/i,
    /\bPARSE_JSON\s*\(/i,
    /\bPARSE_XML\s*\(/i,
    /\bTRY_PARSE_JSON\s*\(/i,
    /\bCHECK_JSON\s*\(/i,
    /\bCHECK_XML\s*\(/i,
    /\bSTRIP_NULL_VALUE\s*\(/i,
    /\bOBJECT_CONSTRUCT\s*\(/i,
    /\bOBJECT_CONSTRUCT_KEEP_NULL\s*\(/i,
    /\bOBJECT_DELETE\s*\(/i,
    /\bOBJECT_INSERT\s*\(/i,
    /\bOBJECT_PICK\s*\(/i,
    /\bARRAY_CONSTRUCT\s*\(/i,
    /\bARRAY_CONSTRUCT_COMPACT\s*\(/i,
    /\bARRAY_APPEND\s*\(/i,
    /\bARRAY_CAT\s*\(/i,
    /\bARRAY_COMPACT\s*\(/i,
    /\bARRAY_CONTAINS\s*\(/i,
    /\bARRAY_DISTINCT\s*\(/i,
    /\bARRAY_EXCEPT\s*\(/i,
    /\bARRAY_FLATTEN\s*\(/i,
    /\bARRAY_GENERATE_RANGE\s*\(/i,
    /\bARRAY_INSERT\s*\(/i,
    /\bARRAY_INTERSECTION\s*\(/i,
    /\bARRAY_POSITION\s*\(/i,
    /\bARRAY_PREPEND\s*\(/i,
    /\bARRAY_REMOVE\s*\(/i,
    /\bARRAY_REMOVE_AT\s*\(/i,
    /\bARRAY_SIZE\s*\(/i,
    /\bARRAY_SLICE\s*\(/i,
    /\bARRAY_SORT\s*\(/i,
    /\bARRAY_TO_STRING\s*\(/i,
    /\bARRAY_UNION\s*\(/i,
    /\bARRAY_UNIQUE_AGG\s*\(/i,
    /\bGET\s*\(/i,
    /\bGET_PATH\s*\(/i,
    /\bFLATTEN\s*\(/i,
    /\bCURRENT_AVAILABLE_ROLES\s*\(\s*\)/i,
    /\bCURRENT_CLIENT\s*\(\s*\)/i,
    /\bCURRENT_DATABASE\s*\(\s*\)/i,
    /\bCURRENT_REGION\s*\(\s*\)/i,
    /\bCURRENT_ROLE\s*\(\s*\)/i,
    /\bCURRENT_SCHEMA\s*\(\s*\)/i,
    /\bCURRENT_SCHEMAS\s*\(\s*\)/i,
    /\bCURRENT_SESSION\s*\(\s*\)/i,
    /\bCURRENT_STATEMENT\s*\(\s*\)/i,
    /\bCURRENT_TIME\s*\(\s*\)/i,
    /\bCURRENT_TIMESTAMP\s*\(\s*\)/i,
    /\bCURRENT_TRANSACTION\s*\(\s*\)/i,
    /\bCURRENT_USER\s*\(\s*\)/i,
    /\bCURRENT_VERSION\s*\(\s*\)/i,
    /\bCURRENT_WAREHOUSE\s*\(\s*\)/i,
    /\bLOCALTIME\s*\(\s*\)/i,
    /\bLOCALTIMESTAMP\s*\(\s*\)/i,
    /\bSYSDATE\s*\(\s*\)/i,
    /\bGETDATE\s*\(\s*\)/i,
    /\bLAST_DAY\s*\(/i,
    /\bNEXT_DAY\s*\(/i,
    /\bPREVIOUS_DAY\s*\(/i,
    /\bDATE_FROM_PARTS\s*\(/i,
    /\bTIME_FROM_PARTS\s*\(/i,
    /\bTIMESTAMP_FROM_PARTS\s*\(/i,
    /\bDAYNAME\s*\(/i,
    /\bMONTHNAME\s*\(/i,
    /\bQUARTER\s*\(/i,
    /\bYEAROFWEEK\s*\(/i,
    /\bYEAROFWEEKISO\s*\(/i,
    /\bWEEKOFYEAR\s*\(/i,
    /\bWEEKISO\s*\(/i,
    /\bDAYOFWEEK\s*\(/i,
    /\bDAYOFWEEKISO\s*\(/i,
    /\bDAYOFYEAR\s*\(/i,
    /\bHOUR\s*\(/i,
    /\bMINUTE\s*\(/i,
    /\bSECOND\s*\(/i,
    /\bNANOSECOND\s*\(/i,
    /\bEPOCH_SECOND\s*\(/i,
    /\bEPOCH_MILLISECOND\s*\(/i,
    /\bEPOCH_MICROSECOND\s*\(/i,
    /\bEPOCH_NANOSECOND\s*\(/i,
    /\bTIMEZONE_HOUR\s*\(/i,
    /\bTIMEZONE_MINUTE\s*\(/i,
    /\bISO_WEEK_START\s*\(/i,
    /\bISO_WEEK_END\s*\(/i,
    /\bWEEK_START\s*\(/i,
    /\bWEEK_END\s*\(/i,
    /\bISO_YEAR_START\s*\(/i,
    /\bISO_YEAR_END\s*\(/i,
    /\bYEAR_START\s*\(/i,
    /\bYEAR_END\s*\(/i,
    /\bCONVERT_TIMEZONE\s*\(/i,
    /\bIFF\s*\(/i,
    /\bZEROIFNULL\s*\(/i,
    /\bNULLIFZERO\s*\(/i,
    /\bEQUAL_NULL\s*\(/i,
    /\bBOOLAND\s*\(/i,
    /\bBOOLOR\s*\(/i,
    /\bBOOLXOR\s*\(/i,
    /\bBOOLNOT\s*\(/i,
    /\bMODE\s*\(/i,
    /\bUNIFORM\s*\(/i,
    /\bNORMAL\s*\(/i,
    /\bSEQ1\s*\(\s*\)/i,
    /\bSEQ2\s*\(\s*\)/i,
    /\bSEQ4\s*\(\s*\)/i,
    /\bSEQ8\s*\(\s*\)/i,
    /\bUUID_STRING\s*\(\s*\)/i,
    /\bRANDOM\s*\(\s*\)/i,
    /\bRRANDOM\s*\(/i,
    /\bZIPF\s*\(/i,
    /\bHASH\s*\(/i,
    /\bSHA1\s*\(/i,
    /\bSHA1_HEX\s*\(/i,
    /\bSHA1_BINARY\s*\(/i,
    /\bSHA2\s*\(/i,
    /\bSHA2_HEX\s*\(/i,
    /\bSHA2_BINARY\s*\(/i,
    /\bMD5\s*\(/i,
    /\bMD5_HEX\s*\(/i,
    /\bMD5_BINARY\s*\(/i,
    /\bMD5_NUMBER\s*\(/i,
    /\bMD5_NUMBER_LOWER64\s*\(/i,
    /\bMD5_NUMBER_UPPER64\s*\(/i,
    /\bBASE64_ENCODE\s*\(/i,
    /\bBASE64_DECODE_STRING\s*\(/i,
    /\bBASE64_DECODE_BINARY\s*\(/i,
    /\bHEX_ENCODE\s*\(/i,
    /\bHEX_DECODE_STRING\s*\(/i,
    /\bHEX_DECODE_BINARY\s*\(/i,
    /\bTRY_BASE64_DECODE_STRING\s*\(/i,
    /\bTRY_BASE64_DECODE_BINARY\s*\(/i,
    /\bTRY_HEX_DECODE_STRING\s*\(/i,
    /\bTRY_HEX_DECODE_BINARY\s*\(/i,
    /\bCOMPRESS\s*\(/i,
    /\bDECOMPRESS_STRING\s*\(/i,
    /\bDECOMPRESS_BINARY\s*\(/i
  ],

  mariadb: [
    // MariaDB specific features (extends MySQL)
    /\bSEQUENCE\b/i,
    /\bROLE\b/i,
    /\bCOLUMN_CHECK\s*\(/i,
    /\bCOLUMN_GET\s*\(/i,
    /\bCOLUMN_JSON\s*\(/i,
    /\bDYNAMIC_COLUMN_\w+\s*\(/i,
    /\bJSON_ARRAY\s*\(/i,
    /\bJSON_ARRAYAGG\s*\(/i,
    /\bJSON_OBJECT\s*\(/i,
    /\bJSON_OBJECTAGG\s*\(/i,
    /\bJSON_EXTRACT\s*\(/i,
    /\bJSON_UNQUOTE\s*\(/i,
    /\bJSON_VALID\s*\(/i,
    /\bGIS\b/i,
    /\bSPIDER\b/i,
    /\bCONNECT\s+ENGINE\b/i,
    /\bFEDERATEDX\b/i,
    /\bCONNECTION\s*=/i,
    /\bVIRTUAL\s+COLUMN\b/i,
    /\bSTORED\s+COLUMN\b/i,
    /\bGENERATED\s+ALWAYS\b/i,
    /\bAUTO_INCREMENT\b/i,
    /\bENGINE\s*=/i,
    /\bCHARSET\s*=/i,
    /\bCOLLATE\s*=/i
  ],

  db2: [
    // IBM DB2 specific features
    /\bIDENTITY\s*\(\s*START\s+WITH\b/i,
    /\bGENERATED\s+ALWAYS\b/i,
    /\bGENERATED\s+BY\s+DEFAULT\b/i,
    /\bDECLARE\s+GLOBAL\s+TEMPORARY\s+TABLE\b/i,
    /\bFINAL\s+TABLE\b/i,
    /\bNEW\s+TABLE\b/i,
    /\bOLD\s+TABLE\b/i,
    /\bDECFLOAT\b/i,
    /\bBIGINT\b/i,
    /\bSMALLINT\b/i,
    /\bREAL\b/i,
    /\bDOUBLE\b/i,
    /\bGRAPHIC\s*\(/i,
    /\bVARGRAPHIC\s*\(/i,
    /\bDBCLOB\s*\(/i,
    /\bXML\b/i,
    /\bROWID\b/i,
    /\bDATE\b/i,
    /\bTIME\b/i,
    /\bTIMESTAMP\b/i,
    /\bVALUES\s+NEXTVAL\s+FOR\b/i,
    /\bVALUES\s+PREVVAL\s+FOR\b/i,
    /\bFETCH\s+FIRST\s+\d+\s+ROWS\s+ONLY\b/i,
    /\bFETCH\s+NEXT\s+\d+\s+ROWS\s+ONLY\b/i,
    /\bROW\s+CHANGE\s+TIMESTAMP\b/i,
    /\bROW\s+BEGIN\b/i,
    /\bROW\s+END\b/i,
    /\bSYSTEM_TIME\b/i,
    /\bBUSINESS_TIME\b/i,
    /\bVERSIONING\b/i,
    /\bWITH\s+ORDINALITY\b/i,
    /\bLATERAL\b/i,
    /\bOVER\s*\(\s*PARTITION\s+BY\b/i,
    /\bRANKING\b/i,
    /\bAGGREGATION\b/i,
    /\bNUMBERING\b/i
  ],

  db2i: [
    // IBM DB2 for i specific features (AS/400)
    /\bAS\/400\b/i,
    /\biSeries\b/i,
    /\bSYSTEM\s+i\b/i,
    /\bQSYS\b/i,
    /\bQTEMP\b/i,
    /\bRCDFMT\b/i,
    /\bDATA\s+AREA\b/i,
    /\bJOURNAL\b/i,
    /\bJRNL\b/i,
    /\bLIBRARY\b/i,
    /\bSCHEMA\b/i,
    /\bCOLLECTION\b/i,
    /\bMEMBER\b/i,
    /\bFILE\b/i,
    /\bRECORD\b/i,
    /\bFIELD\b/i,
    /\bKEYWORD\b/i,
    /\bVALUES\b/i,
    /\bRUNSQLSTM\b/i,
    /\bSTRSQL\b/i,
    /\bINTERACTIVE\s+SQL\b/i,
    /\bSQL\s+REQUEST\b/i,
    /\bSQL\s+PACKAGE\b/i,
    /\bBINDING\b/i,
    /\bACCESS\s+PLAN\b/i,
    /\bOPTIMIZATION\b/i,
    /\bSTAT_VIEW\b/i,
    /\bMQT\b/i,
    /\bMATERIALIZED\s+QUERY\s+TABLE\b/i,
    /\bREFRESH\s+DEFERRED\b/i,
    /\bREFRESH\s+IMMEDIATE\b/i,
    /\bENABLE\s+QUERY\s+OPTIMIZATION\b/i,
    /\bDISABLE\s+QUERY\s+OPTIMIZATION\b/i
  ],

  hive: [
    // Apache Hive specific features
    /\bPARTITIONED\s+BY\b/i,
    /\bCLUSTERED\s+BY\b/i,
    /\bSORTED\s+BY\b/i,
    /\bINTO\s+\d+\s+BUCKETS\b/i,
    /\bSTORED\s+AS\s+ORC\b/i,
    /\bSTORED\s+AS\s+PARQUET\b/i,
    /\bSTORED\s+AS\s+AVRO\b/i,
    /\bSTORED\s+AS\s+RCFILE\b/i,
    /\bSTORED\s+AS\s+SEQUENCEFILE\b/i,
    /\bSTORED\s+AS\s+TEXTFILE\b/i,
    /\bROW\s+FORMAT\s+SERDE\b/i,
    /\bINPUTFORMAT\b/i,
    /\bOUTPUTFORMAT\b/i,
    /\bLOCATION\s+'/i,
    /\bTBLPROPERTIES\s*\(/i,
    /\bSERDEPROPERTIES\s*\(/i,
    /\bADD\s+JAR\b/i,
    /\bADD\s+FILE\b/i,
    /\bADD\s+ARCHIVE\b/i,
    /\bTRANSFORM\b/i,
    /\bUSING\s+'/i,
    /\bAS\s+\(/i,
    /\bLATERAL\s+VIEW\b/i,
    /\bEXPLODE\s*\(/i,
    /\bPOSEXPLODE\s*\(/i,
    /\bINLINE\s*\(/i,
    /\bSTACK\s*\(/i,
    /\bJSON_TUPLE\s*\(/i,
    /\bPARSE_URL\s*\(/i,
    /\bPARSE_URL_TUPLE\s*\(/i,
    /\bXPATH\s*\(/i,
    /\bXPATH_STRING\s*\(/i,
    /\bXPATH_BOOLEAN\s*\(/i,
    /\bXPATH_NUMBER\s*\(/i,
    /\bXPATH_DOUBLE\s*\(/i,
    /\bXPATH_FLOAT\s*\(/i,
    /\bXPATH_INT\s*\(/i,
    /\bXPATH_LONG\s*\(/i,
    /\bXPATH_SHORT\s*\(/i,
    /\bGET_JSON_OBJECT\s*\(/i,
    /\bSTR_TO_MAP\s*\(/i,
    /\bSENTENCES\s*\(/i,
    /\bNGRAMS\s*\(/i,
    /\bCONTEXT_NGRAMS\s*\(/i,
    /\bWORDCOUNT\s*\(/i,
    /\bCOLLECT_LIST\s*\(/i,
    /\bCOLLECT_SET\s*\(/i,
    /\bHISTOGRAM_NUMERIC\s*\(/i,
    /\bPERCENTILE\s*\(/i,
    /\bPERCENTILE_APPROX\s*\(/i,
    /\bUDTF\b/i,
    /\bUDAF\b/i,
    /\bUDF\b/i,
    /\bMAP\s*</i,
    /\bARRAY\s*</i,
    /\bSTRUCT\s*</i,
    /\bUNIONTYPE\s*</i
  ],

  n1ql: [
    // Couchbase N1QL specific features
    /\bFROM\s+\w+\s+USE\s+KEYS\b/i,
    /\bUSE\s+KEYS\b/i,
    /\bUSE\s+INDEX\b/i,
    /\bUSE\s+HASH\s*\(/i,
    /\bUSE\s+NL\b/i,
    /\bBUILD\s+INDEX\b/i,
    /\bCREATE\s+PRIMARY\s+INDEX\b/i,
    /\bCREATE\s+INDEX\b/i,
    /\bDROP\s+PRIMARY\s+INDEX\b/i,
    /\bDROP\s+INDEX\b/i,
    /\bALTER\s+INDEX\b/i,
    /\bEXPLAIN\b/i,
    /\bADVISE\s+INDEX\b/i,
    /\bINFER\b/i,
    /\bPREPARE\b/i,
    /\bEXECUTE\b/i,
    /\bUNNEST\b/i,
    /\bNEST\b/i,
    /\bUNNEST\s+\[\s*SELECT\b/i,
    /\bNEST\s+\[\s*SELECT\b/i,
    /\bANY\s+AND\s+EVERY\b/i,
    /\bANY\b/i,
    /\bEVERY\b/i,
    /\bSATISFIES\b/i,
    /\bWITHIN\b/i,
    /\bCONTAINS\b/i,
    /\bARRAY_AGG\s*\(/i,
    /\bARRAY_APPEND\s*\(/i,
    /\bARRAY_AVG\s*\(/i,
    /\bARRAY_CONCAT\s*\(/i,
    /\bARRAY_CONTAINS\s*\(/i,
    /\bARRAY_COUNT\s*\(/i,
    /\bARRAY_DISTINCT\s*\(/i,
    /\bARRAY_FLATTEN\s*\(/i,
    /\bARRAY_IFNULL\s*\(/i,
    /\bARRAY_INSERT\s*\(/i,
    /\bARRAY_INTERSECT\s*\(/i,
    /\bARRAY_LENGTH\s*\(/i,
    /\bARRAY_MAX\s*\(/i,
    /\bARRAY_MIN\s*\(/i,
    /\bARRAY_POSITION\s*\(/i,
    /\bARRAY_PREPEND\s*\(/i,
    /\bARRAY_PUT\s*\(/i,
    /\bARRAY_RANGE\s*\(/i,
    /\bARRAY_REMOVE\s*\(/i,
    /\bARRAY_REPEAT\s*\(/i,
    /\bARRAY_REPLACE\s*\(/i,
    /\bARRAY_REVERSE\s*\(/i,
    /\bARRAY_SORT\s*\(/i,
    /\bARRAY_STAR\s*\(/i,
    /\bARRAY_SUM\s*\(/i,
    /\bARRAY_SYMDIFF\s*\(/i,
    /\bARRAY_UNION\s*\(/i,
    /\bFIRST\s*\(/i,
    /\bOBJECT_ADD\s*\(/i,
    /\bOBJECT_CONCAT\s*\(/i,
    /\bOBJECT_INNER_PAIRS\s*\(/i,
    /\bOBJECT_INNER_VALUES\s*\(/i,
    /\bOBJECT_NAMES\s*\(/i,
    /\bOBJECT_PAIRS\s*\(/i,
    /\bOBJECT_PUT\s*\(/i,
    /\bOBJECT_REMOVE\s*\(/i,
    /\bOBJECT_RENAME\s*\(/i,
    /\bOBJECT_REPLACE\s*\(/i,
    /\bOBJECT_UNWRAP\s*\(/i,
    /\bOBJECT_VALUES\s*\(/i,
    /\bMETA\s*\(/i,
    /\bBUCKET_NAME\s*\(/i,
    /\bSCOPE_NAME\s*\(/i,
    /\bCOLLECTION_NAME\s*\(/i,
    /\bUUID\s*\(/i,
    /\bTOKENS\s*\(/i,
    /\bTYPE\s*\(/i,
    /\bBASE64\s*\(/i,
    /\bBASE64_ENCODE\s*\(/i,
    /\bBASE64_DECODE\s*\(/i
  ],

  redshift: [
    // Amazon Redshift specific features
    /\bDISTSTYLE\s+(EVEN|KEY|ALL)\b/i,
    /\bDISTKEY\s*\(/i,
    /\bSORTKEY\s*\(/i,
    /\bCOMPOUND\s+SORTKEY\b/i,
    /\bINTERLEAVED\s+SORTKEY\b/i,
    /\bENCODE\s+\w+\b/i,
    /\bCOPY\s+\w+\s+FROM\b/i,
    /\bUNLOAD\s*\(/i,
    /\bVACUUM\b/i,
    /\bANALYZE\b/i,
    /\bWLM_QUERY_SLOT_COUNT\b/i,
    /\bQUERY_GROUP\b/i,
    /\bSEARCH_PATH\b/i,
    /\bDATESHARE\b/i,
    /\bSPECTRUM\b/i,
    /\bEXTERNAL\s+TABLE\b/i,
    /\bEXTERNAL\s+SCHEMA\b/i,
    /\bCREATE\s+EXTERNAL\s+TABLE\b/i,
    /\bSTORED\s+AS\s+PARQUET\b/i,
    /\bSTORED\s+AS\s+ORC\b/i,
    /\bSTORED\s+AS\s+AVRO\b/i,
    /\bSTORED\s+AS\s+RCFILE\b/i,
    /\bSTORED\s+AS\s+SEQUENCEFILE\b/i,
    /\bSTORED\s+AS\s+TEXTFILE\b/i,
    /\bLOCATION\s*'/i,
    /\bTBLPROPERTIES\s*\(/i,
    /\bROW\s+FORMAT\s+SERDE\b/i,
    /\bINPUTFORMAT\b/i,
    /\bOUTPUTFORMAT\b/i,
    /\bAWS_IAM_ROLE\b/i,
    /\bCREDENTIALS\b/i,
    /\bREGION\b/i,
    /\bS3\b/i,
    /\bMANIFEST\b/i,
    /\bDELIMITER\s+AS\b/i,
    /\bFIXED_WIDTH\b/i,
    /\bCSV\b/i,
    /\bGZIP\b/i,
    /\bLZO\b/i,
    /\bBZIP2\b/i,
    /\bIGNORE\s+HEADER\b/i,
    /\bACCEPTINVCHARS\b/i,
    /\bACCEPTANYDATE\b/i,
    /\bBLANKSASNULL\b/i,
    /\bCOMPUPDATE\b/i,
    /\bCOMPRESSUPDATE\b/i,
    /\bDATEFORMAT\b/i,
    /\bTIMEFORMAT\b/i,
    /\bEMPTYASNULL\b/i,
    /\bENCODING\b/i,
    /\bESCAPE\b/i,
    /\bEXPLICIT_IDS\b/i,
    /\bFILLRECORD\b/i,
    /\bIGNOREBLANKLINES\b/i,
    /\bIGNOREHEADER\b/i,
    /\bNULL\s+AS\b/i,
    /\bREMOVEQUOTES\b/i,
    /\bROUNDEC\b/i,
    /\bSTATUPDATE\b/i,
    /\bTIMEFORMAT\b/i,
    /\bTRIMBLANKS\b/i,
    /\bTRUNCATE\s+COLUMNS\b/i,
    /\bMAXERROR\b/i
  ],

  plsql: [
    /\bNUMBER\s*\(/i,
    /\bVARCHAR2\s*\(/i,
    /\bNCHAR\s*\(/i,
    /\bNVARCHAR2\s*\(/i,
    /\bCLOB\b/i,
    /\bNCLOB\b/i,
    /\bBLOB\b/i,
    /\bBFILE\b/i,
    /\bLONG\b/i,
    /\bLONG\s+RAW\b/i,
    /\bRAW\s*\(/i,
    /\bROWID\b/i,
    /\bUROWID\s*\(/i,
    /\bDATE\b/i,
    /\bTIMESTAMP\s*\(/i,
    /\bTIMESTAMP\s+WITH\s+TIME\s+ZONE\s*\(/i,
    /\bTIMESTAMP\s+WITH\s+LOCAL\s+TIME\s+ZONE\s*\(/i,
    /\bINTERVAL\s+YEAR\s*\(/i,
    /\bINTERVAL\s+DAY\s*\(/i,
    /\bBINARY_FLOAT\b/i,
    /\bBINARY_DOUBLE\b/i,
    /\bXMLTYPE\b/i,
    /\bSDO_GEOMETRY\b/i,
    /\bSYS_REFCURSOR\b/i,
    /\bCONNECT\s+BY\b/i,
    /\bSTART\s+WITH\b/i,
    /\bPRIOR\b/i,
    /\bLEVEL\b/i,
    /\bROWNUM\b/i,
    /\bROWID\b/i,
    /\bNVL\s*\(/i,
    /\bNVL2\s*\(/i,
    /\bDECODE\s*\(/i,
    /\bGREATEST\s*\(/i,
    /\bLEAST\s*\(/i,
    /\bSYSDATE\b/i,
    /\bCURRENT_DATE\b/i,
    /\bCURRENT_TIMESTAMP\b/i,
    /\bLOCALTIMESTAMP\b/i,
    /\bSYSTIMESTAMP\b/i,
    /\bEXTRACT\s*\(/i,
    /\bTO_DATE\s*\(/i,
    /\bTO_CHAR\s*\(/i,
    /\bTO_NUMBER\s*\(/i,
    /\bTO_CLOB\s*\(/i,
    /\bTO_BLOB\s*\(/i,
    /\bADD_MONTHS\s*\(/i,
    /\bMONTHS_BETWEEN\s*\(/i,
    /\bNEXT_DAY\s*\(/i,
    /\bLAST_DAY\s*\(/i,
    /\bTRUNC\s*\(/i,
    /\bROUND\s*\(/i,
    /\bMOD\s*\(/i,
    /\bABS\s*\(/i,
    /\bCEIL\s*\(/i,
    /\bFLOOR\s*\(/i,
    /\bPOWER\s*\(/i,
    /\bSQRT\s*\(/i,
    /\bEXP\s*\(/i,
    /\bLN\s*\(/i,
    /\bLOG\s*\(/i,
    /\bSIN\s*\(/i,
    /\bCOS\s*\(/i,
    /\bTAN\s*\(/i,
    /\bASIN\s*\(/i,
    /\bACOS\s*\(/i,
    /\bATAN\s*\(/i,
    /\bATAN2\s*\(/i,
    /\bSIGN\s*\(/i,
    /\bSUBSTR\s*\(/i,
    /\bINSTR\s*\(/i,
    /\bLENGTH\s*\(/i,
    /\bCONCAT\s*\(/i,
    /\bUPPER\s*\(/i,
    /\bLOWER\s*\(/i,
    /\bINITCAP\s*\(/i,
    /\bLTRIM\s*\(/i,
    /\bRTRIM\s*\(/i,
    /\bTRIM\s*\(/i,
    /\bLPAD\s*\(/i,
    /\bRPAD\s*\(/i,
    /\bREPLACE\s*\(/i,
    /\bTRANSLATE\s*\(/i,
    /\bSOUNDEX\s*\(/i,
    /\bASCII\s*\(/i,
    /\bCHR\s*\(/i,
    /\bREVERSE\s*\(/i,
    /\bROW_NUMBER\s*\(\s*\)\s+OVER\s*\(/i,
    /\bRANK\s*\(\s*\)\s+OVER\s*\(/i,
    /\bDENSE_RANK\s*\(\s*\)\s+OVER\s*\(/i,
    /\bPERCENT_RANK\s*\(\s*\)\s+OVER\s*\(/i,
    /\bCUME_DIST\s*\(\s*\)\s+OVER\s*\(/i,
    /\bNTILE\s*\(/i,
    /\bFIRST_VALUE\s*\(/i,
    /\bLAST_VALUE\s*\(/i,
    /\bLAG\s*\(/i,
    /\bLEAD\s*\(/i,
    /\bFIRST\s*\(/i,
    /\bLAST\s*\(/i,
    /\bLISTAGG\s*\(/i,
    /\bWM_CONCAT\s*\(/i,
    /\bREGEXP_LIKE\s*\(/i,
    /\bREGEXP_REPLACE\s*\(/i,
    /\bREGEXP_SUBSTR\s*\(/i,
    /\bREGEXP_INSTR\s*\(/i,
    /\bREGEXP_COUNT\s*\(/i,
    /\bXMLFOREST\s*\(/i,
    /\bXMLELEMENT\s*\(/i,
    /\bXMLAGG\s*\(/i,
    /\bXMLCONCAT\s*\(/i,
    /\bXMLPARSE\s*\(/i,
    /\bXMLSERIALIZE\s*\(/i,
    /\bXMLQUERY\s*\(/i,
    /\bXMLTABLE\s*\(/i,
    /\bEXTRACTVALUE\s*\(/i,
    /\bXMLTRANSFORM\s*\(/i,
    /\bUPDATE.*RETURNING\b/i,
    /\bDELETE.*RETURNING\b/i,
    /\bINSERT.*RETURNING\b/i,
    /\bMERGE\b/i,
    /\bWHEN\s+MATCHED\b/i,
    /\bWHEN\s+NOT\s+MATCHED\b/i,
    /\bUSING\b/i,
    /\bDUAL\b/i,
    /\bFROM\s+DUAL\b/i,
    /\bWHERE\s+1\s*=\s*1\b/i,
    /\bPLSQL\b/i,
    /\bDECLARE\b/i,
    /\bBEGIN\b/i,
    /\bEND\s*;/i,
    /\bEXCEPTION\b/i,
    /\bWHEN\s+OTHERS\b/i,
    /\bRAISE\b/i,
    /\bRAISE_APPLICATION_ERROR\s*\(/i,
    /\bDBMS_OUTPUT\.PUT_LINE\s*\(/i,
    /\bIF\s+.*\s+THEN\b/i,
    /\bELSIF\b/i,
    /\bELSE\b/i,
    /\bEND\s+IF\s*;/i,
    /\bLOOP\b/i,
    /\bEND\s+LOOP\s*;/i,
    /\bWHILE\s+.*\s+LOOP\b/i,
    /\bFOR\s+.*\s+IN\s+.*\s+LOOP\b/i,
    /\bEXIT\s+WHEN\b/i,
    /\bCURSOR\b/i,
    /\bOPEN\b/i,
    /\bFETCH\b/i,
    /\bCLOSE\b/i,
    /\b%TYPE\b/i,
    /\b%ROWTYPE\b/i,
    /\bFORCE\b/i,
    /\bNOFORCE\b/i,
    /\bVIEW\b/i,
    /\bMATERIALIZED\s+VIEW\b/i,
    /\bSEQUENCE\b/i,
    /\bNEXTVAL\b/i,
    /\bCURRVAL\b/i,
    /\bSYNONYM\b/i,
    /\bDBLINK\b/i,
    /\bTABLESPACE\b/i,
    /\bINDEX\b/i,
    /\bUNIQUE\s+INDEX\b/i,
    /\bBITMAP\s+INDEX\b/i,
    /\bFUNCTION\b/i,
    /\bPROCEDURE\b/i,
    /\bPACKAGE\b/i,
    /\bTRIGGER\b/i,
    /\bBEFORE\s+INSERT\b/i,
    /\bAFTER\s+INSERT\b/i,
    /\bBEFORE\s+UPDATE\b/i,
    /\bAFTER\s+UPDATE\b/i,
    /\bBEFORE\s+DELETE\b/i,
    /\bAFTER\s+DELETE\b/i,
    /\bINSTEAD\s+OF\b/i,
    /\bFOR\s+EACH\s+ROW\b/i,
    /\bWHEN\s*\(/i,
    /\b:NEW\./i,
    /\b:OLD\./i,
    /\bINSERTING\b/i,
    /\bUPDATING\b/i,
    /\bDELETING\b/i,
    /\bGRANT\b/i,
    /\bREVOKE\b/i,
    /\bCOMMIT\b/i,
    /\bROLLBACK\b/i,
    /\bSAVEPOINT\b/i,
    /\bSET\s+TRANSACTION\b/i,
    /\bSELECT\s+.*\s+FOR\s+UPDATE\b/i,
    /\bLOCK\s+TABLE\b/i,
    /\bALTER\s+SESSION\b/i,
    /\bALTER\s+SYSTEM\b/i,
    /\bEXPLAIN\s+PLAN\b/i,
    /\bAUTOTRACE\b/i,
    /\bSET\s+SERVEROUTPUT\s+ON\b/i,
    /\bSET\s+ECHO\s+ON\b/i,
    /\bSET\s+FEEDBACK\s+ON\b/i,
    /\bSET\s+HEADING\s+ON\b/i,
    /\bSET\s+LINESIZE\b/i,
    /\bSET\s+PAGESIZE\b/i,
    /\bSPOOL\b/i,
    /\bDESC\b/i,
    /\bDESCRIBE\b/i,
    /\bSHOW\s+ERRORS\b/i,
    /\bSHOW\s+PARAMETERS\b/i,
    /\bSELECT\s+\*\s+FROM\s+ALL_TABLES\b/i,
    /\bSELECT\s+\*\s+FROM\s+USER_TABLES\b/i,
    /\bSELECT\s+\*\s+FROM\s+DBA_TABLES\b/i,
    /\bSELECT\s+\*\s+FROM\s+ALL_TAB_COLUMNS\b/i,
    /\bSELECT\s+\*\s+FROM\s+USER_TAB_COLUMNS\b/i,
    /\bSELECT\s+\*\s+FROM\s+DBA_TAB_COLUMNS\b/i,
    /\bSELECT\s+\*\s+FROM\s+ALL_INDEXES\b/i,
    /\bSELECT\s+\*\s+FROM\s+USER_INDEXES\b/i,
    /\bSELECT\s+\*\s+FROM\s+DBA_INDEXES\b/i,
    /\bSELECT\s+\*\s+FROM\s+ALL_IND_COLUMNS\b/i,
    /\bSELECT\s+\*\s+FROM\s+USER_IND_COLUMNS\b/i,
    /\bSELECT\s+\*\s+FROM\s+DBA_IND_COLUMNS\b/i,
    /\bSELECT\s+\*\s+FROM\s+ALL_CONSTRAINTS\b/i,
    /\bSELECT\s+\*\s+FROM\s+USER_CONSTRAINTS\b/i,
    /\bSELECT\s+\*\s+FROM\s+DBA_CONSTRAINTS\b/i,
    /\bSELECT\s+\*\s+FROM\s+ALL_CONS_COLUMNS\b/i,
    /\bSELECT\s+\*\s+FROM\s+USER_CONS_COLUMNS\b/i,
    /\bSELECT\s+\*\s+FROM\s+DBA_CONS_COLUMNS\b/i,
    /\bSELECT\s+\*\s+FROM\s+ALL_SEQUENCES\b/i,
    /\bSELECT\s+\*\s+FROM\s+USER_SEQUENCES\b/i,
    /\bSELECT\s+\*\s+FROM\s+DBA_SEQUENCES\b/i,
    /\bSELECT\s+\*\s+FROM\s+ALL_VIEWS\b/i,
    /\bSELECT\s+\*\s+FROM\s+USER_VIEWS\b/i,
    /\bSELECT\s+\*\s+FROM\s+DBA_VIEWS\b/i,
    /\bSELECT\s+\*\s+FROM\s+ALL_SYNONYMS\b/i,
    /\bSELECT\s+\*\s+FROM\s+USER_SYNONYMS\b/i,
    /\bSELECT\s+\*\s+FROM\s+DBA_SYNONYMS\b/i,
    /\bSELECT\s+\*\s+FROM\s+ALL_OBJECTS\b/i,
    /\bSELECT\s+\*\s+FROM\s+USER_OBJECTS\b/i,
    /\bSELECT\s+\*\s+FROM\s+DBA_OBJECTS\b/i,
    /\bSELECT\s+\*\s+FROM\s+ALL_SOURCE\b/i,
    /\bSELECT\s+\*\s+FROM\s+USER_SOURCE\b/i,
    /\bSELECT\s+\*\s+FROM\s+DBA_SOURCE\b/i,
    /\bSELECT\s+\*\s+FROM\s+ALL_TRIGGERS\b/i,
    /\bSELECT\s+\*\s+FROM\s+USER_TRIGGERS\b/i,
    /\bSELECT\s+\*\s+FROM\s+DBA_TRIGGERS\b/i,
    /\bV\$SESSION\b/i,
    /\bV\$PROCESS\b/i,
    /\bV\$DATABASE\b/i,
    /\bV\$INSTANCE\b/i,
    /\bV\$PARAMETER\b/i,
    /\bV\$SQLAREA\b/i,
    /\bV\$SQL\b/i,
    /\bV\$LOCK\b/i,
    /\bV\$LOCKED_OBJECT\b/i,
    /\bV\$TRANSACTION\b/i,
    /\bV\$ROLLSTAT\b/i,
    /\bV\$ROWCACHE\b/i,
    /\bV\$SGASTAT\b/i,
    /\bV\$SYSSTAT\b/i,
    /\bV\$SESSTAT\b/i,
    /\bV\$STATNAME\b/i,
    /\bV\$WAITSTAT\b/i,
    /\bV\$SYSTEM_EVENT\b/i,
    /\bV\$SESSION_EVENT\b/i,
    /\bV\$EVENT_NAME\b/i,
    /\bV\$ACTIVE_SESSION_HISTORY\b/i,
    /\bV\$SQL_PLAN\b/i,
    /\bV\$SQL_PLAN_STATISTICS\b/i,
    /\bV\$SQL_PLAN_STATISTICS_ALL\b/i,
    /\bV\$SQLSTATS\b/i,
    /\bV\$SQLTEXT\b/i,
    /\bV\$SQLTEXT_WITH_NEWLINES\b/i
  ]
};

/**
 * 根据SQL语句自动检测SQL方言
 * @param {string} sql - SQL语句
 * @returns {string} - 检测到的SQL方言，默认为'sql'
 */
export function detectDialect(sql) {
  if (!sql || typeof sql !== 'string') {
    return 'sql';
  }

  const normalizedSql = sql.trim();
  if (normalizedSql.length === 0) {
    return 'sql';
  }

  // 计算每个方言的匹配得分
  const scores = {};
  
  for (const [dialect, patterns] of Object.entries(dialectPatterns)) {
    scores[dialect] = 0;
    
    for (const pattern of patterns) {
      if (pattern.test(normalizedSql)) {
        scores[dialect]++;
      }
    }
  }

  // 找出得分最高的方言
  let bestDialect = 'sql';
  let highestScore = 0;

  for (const [dialect, score] of Object.entries(scores)) {
    if (score > highestScore) {
      bestDialect = dialect;
      highestScore = score;
    }
  }

  // 如果没有明显的特征，尝试通用检测
  if (highestScore === 0) {
    return detectGenericFeatures(normalizedSql);
  }

  return bestDialect;
}

/**
 * 通用特征检测
 * @param {string} sql - SQL语句
 * @returns {string} - 检测到的SQL方言
 */
function detectGenericFeatures(sql) {
  const upperSql = sql.toUpperCase();
  
  // 检测一些通用但有倾向性的特征
  if (upperSql.includes('LIMIT') && upperSql.includes('OFFSET')) {
    if (upperSql.includes('AUTO_INCREMENT') || upperSql.includes('ENGINE=')) {
      return 'mysql';
    }
    return 'postgresql';
  }
  
  if (upperSql.includes('TOP ') && (upperSql.includes('IDENTITY') || upperSql.includes('NVARCHAR'))) {
    return 'transactsql';
  }
  
  if (upperSql.includes('ROWNUM') || upperSql.includes('DUAL')) {
    return 'plsql';
  }
  
  if (upperSql.includes('PRAGMA') || upperSql.includes('AUTOINCREMENT')) {
    return 'sqlite';
  }
  
  if (upperSql.includes('STRUCT<') || upperSql.includes('ARRAY<')) {
    return 'bigquery';
  }
  
  if (upperSql.includes('VARIANT') || upperSql.includes('$1') || upperSql.includes('QUALIFY')) {
    return 'snowflake';
  }
  
  if (upperSql.includes('PARTITIONED BY') || upperSql.includes('STORED AS ORC') || upperSql.includes('LATERAL VIEW')) {
    return 'hive';
  }
  
  if (upperSql.includes('USE KEYS') || upperSql.includes('UNNEST') && upperSql.includes('SATISFIES')) {
    return 'n1ql';
  }
  
  if (upperSql.includes('DISTSTYLE') || upperSql.includes('SORTKEY') || upperSql.includes('DISTKEY')) {
    return 'redshift';
  }
  
  if (upperSql.includes('COLUMNSTORE') || upperSql.includes('SHARD KEY') || upperSql.includes('REFERENCE TABLE')) {
    return 'singlestoredb';
  }
  
  if (upperSql.includes('CACHE TABLE') || upperSql.includes('BROADCAST(') || upperSql.includes('USING DELTA')) {
    return 'spark';
  }
  
  if (upperSql.includes('TIDB_VERSION') || upperSql.includes('AUTO_RANDOM') || upperSql.includes('AS OF TIMESTAMP')) {
    return 'tidb';
  }
  
  if (upperSql.includes('ARRAY[') || upperSql.includes('MAP(') || upperSql.includes('APPROX_DISTINCT')) {
    return 'trino';
  }
  
  if (upperSql.includes('DECFLOAT') || upperSql.includes('GENERATED ALWAYS') || upperSql.includes('FINAL TABLE')) {
    return 'db2';
  }
  
  if (upperSql.includes('QSYS') || upperSql.includes('JOURNAL') || upperSql.includes('AS/400')) {
    return 'db2i';
  }
  
  if (upperSql.includes('JSON_EXTRACT') && (upperSql.includes('ENGINE=') || upperSql.includes('SEQUENCE'))) {
    return 'mariadb';
  }
  
  // 默认返回通用SQL
  return 'sql';
}
