// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BackupService 提供基于Git的备份同步功能
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * HandleConfigChange 处理配置变更
 */
export function HandleConfigChange(config: models$0.GitBackupConfig | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(395287784, config) as any;
    return $resultPromise;
}

/**
 * Initialize 初始化备份服务
 */
export function Initialize(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1052437974) as any;
    return $resultPromise;
}

/**
 * Reinitialize 重新初始化
 */
export function Reinitialize(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(301562543) as any;
    return $resultPromise;
}

/**
 * ServiceShutdown 服务关闭
 */
export function ServiceShutdown(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(422131801) as any;
    return $resultPromise;
}

export function ServiceStartup(options: application$0.ServiceOptions): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2900331732, options) as any;
    return $resultPromise;
}

/**
 * StartAutoBackup 启动自动备份
 */
export function StartAutoBackup(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3035755449) as any;
    return $resultPromise;
}

/**
 * StopAutoBackup 停止自动备份
 */
export function StopAutoBackup(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2641894021) as any;
    return $resultPromise;
}

/**
 * Sync 执行完整的同步流程：导出 -> commit -> pull -> 解决冲突 -> push -> 导入
 */
export function Sync(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3420383211) as any;
    return $resultPromise;
}
