// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DatabaseService provides shared database functionality
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../database/sql/models.js";

/**
 * GetDB returns the database connection
 */
export function GetDB(): Promise<sql$0.DB | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(228760371) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * OnDataPathChanged handles data path changes
 */
export function OnDataPathChanged(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3652863491) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = sql$0.DB.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
