// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DatabaseService provides shared database functionality
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * OnDataPathChanged handles data path changes
 */
export function OnDataPathChanged(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3652863491) as any;
    return $resultPromise;
}

/**
 * ServiceShutdown shuts down the service when the application closes
 */
export function ServiceShutdown(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3907893632) as any;
    return $resultPromise;
}

/**
 * ServiceStartup initializes the service when the application starts
 */
export function ServiceStartup(options: application$0.ServiceOptions): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2067840771, options) as any;
    return $resultPromise;
}
