// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExtensionService 扩展服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ent$0 from "../models/ent/models.js";

/**
 * GetDefaultExtensions 获取默认扩展配置（用于前端绑定生成）
 */
export function GetDefaultExtensions(): Promise<models$0.Extension[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4036328166) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetExtensionByID 根据ID获取扩展
 */
export function GetExtensionByID(id: number): Promise<ent$0.Extension | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1521424252, id) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetExtensionConfig 获取扩展配置
 */
export function GetExtensionConfig(id: number): Promise<{ [_: string]: any }> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1629559882, id) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType4($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetExtensions 获取所有扩展
 */
export function GetExtensions(): Promise<(ent$0.Extension | null)[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3179289021) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType5($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ResetExtensionConfig 重置单个扩展到默认状态
 */
export function ResetExtensionConfig(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3990780299, id) as any;
    return $resultPromise;
}

/**
 * ServiceStartup 服务启动
 */
export function ServiceStartup(options: application$0.ServiceOptions): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(40324057, options) as any;
    return $resultPromise;
}

/**
 * SyncExtensions 同步扩展配置
 */
export function SyncExtensions(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(167560004) as any;
    return $resultPromise;
}

/**
 * UpdateExtensionConfig 更新扩展配置
 */
export function UpdateExtensionConfig(id: number, config: { [_: string]: any }): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3184142503, id, config) as any;
    return $resultPromise;
}

/**
 * UpdateExtensionEnabled 更新扩展启用状态
 */
export function UpdateExtensionEnabled(id: number, enabled: boolean): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1067300094, id, enabled) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = models$0.Extension.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ent$0.Extension.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $Create.Array($$createType3);
