// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExtensionService 扩展管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * DisableExtension 禁用扩展
 */
export function DisableExtension(id: models$0.ExtensionID): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2040844784, id) as any;
    return $resultPromise;
}

/**
 * EnableExtension 启用扩展
 */
export function EnableExtension(id: models$0.ExtensionID): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2926319443, id) as any;
    return $resultPromise;
}

/**
 * GetAllExtensions 获取所有扩展配置
 */
export function GetAllExtensions(): Promise<models$0.Extension[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3094292124) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetExtensionSettings 获取完整扩展配置
 */
export function GetExtensionSettings(): Promise<models$0.ExtensionSettings | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2127854337) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ResetAllExtensionsToDefault 重置所有扩展到默认状态
 */
export function ResetAllExtensionsToDefault(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(270611949) as any;
    return $resultPromise;
}

/**
 * ResetExtensionToDefault 重置扩展到默认状态
 */
export function ResetExtensionToDefault(id: models$0.ExtensionID): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(868308101, id) as any;
    return $resultPromise;
}

/**
 * ServiceShutdown 关闭服务
 */
export function ServiceShutdown(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4127635746) as any;
    return $resultPromise;
}

/**
 * UpdateExtensionState 更新扩展状态
 */
export function UpdateExtensionState(id: models$0.ExtensionID, enabled: boolean, config: models$0.ExtensionConfig): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2917946454, id, enabled, config) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = models$0.Extension.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = models$0.ExtensionSettings.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
