// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExtensionService 扩展服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ent$0 from "../models/ent/models.js";

/**
 * GetDefaultExtensions 获取默认扩展配置（用于前端绑定生成）
 */
export function GetDefaultExtensions(): $CancellablePromise<models$0.Extension[]> {
    return $Call.ByID(4036328166).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetExtensionByID 根据ID获取扩展
 */
export function GetExtensionByID(id: number): $CancellablePromise<ent$0.Extension | null> {
    return $Call.ByID(1521424252, id).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetExtensionConfig 获取扩展配置
 */
export function GetExtensionConfig(id: number): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1629559882, id).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetExtensions 获取所有扩展
 */
export function GetExtensions(): $CancellablePromise<(ent$0.Extension | null)[]> {
    return $Call.ByID(3179289021).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ResetExtensionConfig 重置单个扩展到默认状态
 */
export function ResetExtensionConfig(id: number): $CancellablePromise<void> {
    return $Call.ByID(3990780299, id);
}

/**
 * SyncExtensions 同步扩展配置
 */
export function SyncExtensions(): $CancellablePromise<void> {
    return $Call.ByID(167560004);
}

/**
 * UpdateExtensionConfig 更新扩展配置
 */
export function UpdateExtensionConfig(id: number, config: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(3184142503, id, config);
}

/**
 * UpdateExtensionEnabled 更新扩展启用状态
 */
export function UpdateExtensionEnabled(id: number, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1067300094, id, enabled);
}

// Private type creation functions
const $$createType0 = models$0.Extension.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ent$0.Extension.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $Create.Array($$createType3);
