// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HotkeyService 全局热键服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * GetSupportedKeys 返回系统支持的快捷键列表
 */
export function GetSupportedKeys(): $CancellablePromise<string[]> {
    return $Call.ByID(1511528650).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Initialize 初始化热键服务
 */
export function Initialize(): $CancellablePromise<void> {
    return $Call.ByID(3671360458);
}

/**
 * IsRegistered 检查是否已注册
 */
export function IsRegistered(): $CancellablePromise<boolean> {
    return $Call.ByID(106954156);
}

/**
 * RegisterHotkey 注册全局热键
 */
export function RegisterHotkey(combo: models$0.HotkeyCombo | null): $CancellablePromise<void> {
    return $Call.ByID(1103945691, combo);
}

/**
 * UnregisterHotkey 取消注册全局热键
 */
export function UnregisterHotkey(): $CancellablePromise<void> {
    return $Call.ByID(3544283732);
}

/**
 * UpdateHotkey 更新热键配置
 */
export function UpdateHotkey(enable: boolean, combo: models$0.HotkeyCombo | null): $CancellablePromise<void> {
    return $Call.ByID(823285555, enable, combo);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
