// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * MemoryStats 内存统计信息
 */
export class MemoryStats {
    /**
     * 当前堆内存使用量（字节）
     */
    "heapInUse": number;

    /**
     * 堆内存分配总量（字节）
     */
    "heapAlloc": number;

    /**
     * 系统内存使用量（字节）
     */
    "sys": number;

    /**
     * GC 次数
     */
    "numGC": number;

    /**
     * GC 暂停时间（纳秒）
     */
    "pauseTotalNs": number;

    /**
     * Goroutine 数量
     */
    "numGoroutine": number;

    /** Creates a new MemoryStats instance. */
    constructor($$source: Partial<MemoryStats> = {}) {
        if (!("heapInUse" in $$source)) {
            this["heapInUse"] = 0;
        }
        if (!("heapAlloc" in $$source)) {
            this["heapAlloc"] = 0;
        }
        if (!("sys" in $$source)) {
            this["sys"] = 0;
        }
        if (!("numGC" in $$source)) {
            this["numGC"] = 0;
        }
        if (!("pauseTotalNs" in $$source)) {
            this["pauseTotalNs"] = 0;
        }
        if (!("numGoroutine" in $$source)) {
            this["numGoroutine"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryStats instance from a string or object.
     */
    static createFrom($$source: any = {}): MemoryStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryStats($$parsedSource as Partial<MemoryStats>);
    }
}

/**
 * MigrationProgress 迁移进度信息
 */
export class MigrationProgress {
    /**
     * 迁移状态
     */
    "status": MigrationStatus;

    /**
     * 当前处理的文件
     */
    "currentFile": string;

    /**
     * 已处理文件数
     */
    "processedFiles": number;

    /**
     * 总文件数
     */
    "totalFiles": number;

    /**
     * 已处理字节数
     */
    "processedBytes": number;

    /**
     * 总字节数
     */
    "totalBytes": number;

    /**
     * 进度百分比 (0-100)
     */
    "progress": number;

    /**
     * 状态消息
     */
    "message": string;

    /**
     * 错误信息
     */
    "error"?: string;

    /**
     * 开始时间
     */
    "startTime": time$0.Time;

    /**
     * 估计剩余时间
     */
    "estimatedTime": time$0.Duration;

    /** Creates a new MigrationProgress instance. */
    constructor($$source: Partial<MigrationProgress> = {}) {
        if (!("status" in $$source)) {
            this["status"] = ("" as MigrationStatus);
        }
        if (!("currentFile" in $$source)) {
            this["currentFile"] = "";
        }
        if (!("processedFiles" in $$source)) {
            this["processedFiles"] = 0;
        }
        if (!("totalFiles" in $$source)) {
            this["totalFiles"] = 0;
        }
        if (!("processedBytes" in $$source)) {
            this["processedBytes"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("startTime" in $$source)) {
            this["startTime"] = null;
        }
        if (!("estimatedTime" in $$source)) {
            this["estimatedTime"] = (0 as time$0.Duration);
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MigrationProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): MigrationProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MigrationProgress($$parsedSource as Partial<MigrationProgress>);
    }
}

/**
 * MigrationProgressCallback 进度回调函数类型
 */
export type MigrationProgressCallback = any;

/**
 * MigrationStatus 迁移状态
 */
export enum MigrationStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 空闲状态
     */
    MigrationStatusIdle = "idle",

    /**
     * 准备中
     */
    MigrationStatusPreparing = "preparing",

    /**
     * 迁移中
     */
    MigrationStatusMigrating = "migrating",

    /**
     * 完成
     */
    MigrationStatusCompleted = "completed",

    /**
     * 失败
     */
    MigrationStatusFailed = "failed",

    /**
     * 取消
     */
    MigrationStatusCancelled = "cancelled",
};
