// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SyncService exposes app-layer sync operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * HandleConfigChange re-applies sync config changes.
 */
export function HandleConfigChange(config: models$0.SyncConfig | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1326966557, config) as any;
    return $resultPromise;
}

/**
 * Initialize reloads config and restarts auto-sync.
 */
export function Initialize(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1986210239) as any;
    return $resultPromise;
}

/**
 * ListSyncRunLogs returns paginated sync execution records.
 */
export function ListSyncRunLogs(page: number, pageSize: number): Promise<models$0.SyncRunRecord[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(990538328, page, pageSize) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * Reinitialize is an alias used by config watchers.
 */
export function Reinitialize(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1904005378) as any;
    return $resultPromise;
}

/**
 * ServiceShutdown stops observers and sync schedulers.
 */
export function ServiceShutdown(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4185231442) as any;
    return $resultPromise;
}

/**
 * ServiceStartup initializes the sync service and config observers.
 */
export function ServiceStartup(options: application$0.ServiceOptions): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2650385641, options) as any;
    return $resultPromise;
}

/**
 * StartAutoSync starts auto-sync scheduling.
 */
export function StartAutoSync(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(90694923) as any;
    return $resultPromise;
}

/**
 * StopAutoSync stops auto-sync scheduling.
 */
export function StopAutoSync(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(972414697) as any;
    return $resultPromise;
}

/**
 * Sync runs one manual sync.
 */
export function Sync(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3361086502) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = models$0.SyncRunRecord.createFrom;
const $$createType1 = $Create.Array($$createType0);
