// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService 系统监控服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FormatBytes 格式化字节数为人类可读的格式
 */
export function FormatBytes(bytes: number): $CancellablePromise<string> {
    return $Call.ByID(1368998019, bytes);
}

/**
 * GetMemoryStats 获取当前内存统计信息
 */
export function GetMemoryStats(): $CancellablePromise<$models.MemoryStats> {
    return $Call.ByID(1678201009).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetSystemInfo 获取系统环境信息
 */
export function GetSystemInfo(): $CancellablePromise<$models.SystemInfo | null> {
    return $Call.ByID(2629436820).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * TriggerGC 手动触发垃圾回收
 */
export function TriggerGC(): $CancellablePromise<void> {
    return $Call.ByID(741882899);
}

// Private type creation functions
const $$createType0 = $models.MemoryStats.createFrom;
const $$createType1 = $models.SystemInfo.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
