// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TestService 测试服务 - 仅在开发环境使用
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ClearAll 清除所有测试状态
 */
export function ClearAll(): $CancellablePromise<void> {
    return $Call.ByID(2179720854);
}

/**
 * TestBadge 测试Badge功能
 */
export function TestBadge(text: string): $CancellablePromise<void> {
    return $Call.ByID(4242952145, text);
}

/**
 * TestNotification 测试通知功能
 */
export function TestNotification(title: string, subtitle: string, body: string): $CancellablePromise<void> {
    return $Call.ByID(1697553289, title, subtitle, body);
}

/**
 * TestUpdateNotification 测试更新通知
 */
export function TestUpdateNotification(): $CancellablePromise<void> {
    return $Call.ByID(3091730060);
}
