// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ThemeService 主题服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ent$0 from "../models/ent/models.js";

/**
 * GetThemeByName 根据Key获取主题
 */
export function GetThemeByName(name: string): $CancellablePromise<ent$0.Theme | null> {
    return $Call.ByID(1938954770, name).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ResetTheme 删除主题
 */
export function ResetTheme(key: string): $CancellablePromise<void> {
    return $Call.ByID(1806334457, key);
}

/**
 * UpdateTheme 保存或更新主题
 */
export function UpdateTheme(key: string, colors: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(70189749, key, colors);
}

// Private type creation functions
const $$createType0 = ent$0.Theme.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
