// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrayService 系统托盘服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * HandleWindowClose 处理窗口关闭事件
 */
export function HandleWindowClose(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1824247204) as any;
    return $resultPromise;
}

/**
 * HandleWindowMinimize 处理窗口最小化事件
 */
export function HandleWindowMinimize(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(178686624) as any;
    return $resultPromise;
}

/**
 * MinimizeButtonClicked 处理标题栏最小化按钮点击
 */
export function MinimizeButtonClicked(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2477618539) as any;
    return $resultPromise;
}

/**
 * SetAppReferences 设置应用引用
 */
export function SetAppReferences(app: application$0.App | null, mainWindow: application$0.WebviewWindow | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3544515719, app, mainWindow) as any;
    return $resultPromise;
}

/**
 * ShouldMinimizeToTray 检查是否应该最小化到托盘
 */
export function ShouldMinimizeToTray(): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3403884012) as any;
    return $resultPromise;
}

/**
 * ShowWindow 显示主窗口
 */
export function ShowWindow(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1315913255) as any;
    return $resultPromise;
}
