// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService 窗口管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * IsDocumentWindowOpen 检查指定文档的窗口是否已打开
 */
export function IsDocumentWindowOpen(documentID: number): $CancellablePromise<boolean> {
    return $Call.ByID(1735611839, documentID);
}

/**
 * OpenDocumentWindow 为指定文档ID打开新窗口
 */
export function OpenDocumentWindow(documentID: number): $CancellablePromise<void> {
    return $Call.ByID(494716471, documentID);
}
