// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  indent = 16,
  LineText1 = 1,
  LineText2 = 2,
  LineText3 = 3,
  LineText4 = 4,
  LineText5 = 5,
  newline = 17,
  newlineEmpty = 18,
  MindmapDiagram = 6,
  DiagramName = 7,
  Line = 8,
  IconLine = 9,
  Icon = 10,
  ClassLine = 11,
  ShapedText = 12
