// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service represents the notifications service
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * RemoveBadge removes the badge label from the application icon.
 */
export function RemoveBadge(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2374916939) as any;
    return $resultPromise;
}

/**
 * ServiceName returns the name of the service.
 */
export function ServiceName(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2428202016) as any;
    return $resultPromise;
}

/**
 * ServiceShutdown is called when the service is unloaded.
 */
export function ServiceShutdown(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3893755233) as any;
    return $resultPromise;
}

/**
 * ServiceStartup is called when the service is loaded.
 */
export function ServiceStartup(options: application$0.ServiceOptions): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4078800764, options) as any;
    return $resultPromise;
}

/**
 * SetBadge sets the badge label on the application icon.
 */
export function SetBadge(label: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(784276339, label) as any;
    return $resultPromise;
}

export function SetCustomBadge(label: string, options: $models.Options): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3058653106, label, options) as any;
    return $resultPromise;
}
