// Code generated by ent, DO NOT EDIT.

package mediaasset

import (
	"voidraft/internal/models/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldDeletedAt, v))
}

// UUID applies equality check predicate on the "uuid" field. It's identical to UUIDEQ.
func UUID(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldUUID, v))
}

// AssetID applies equality check predicate on the "asset_id" field. It's identical to AssetIDEQ.
func AssetID(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldAssetID, v))
}

// OriginalFilename applies equality check predicate on the "original_filename" field. It's identical to OriginalFilenameEQ.
func OriginalFilename(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldOriginalFilename, v))
}

// RelativePath applies equality check predicate on the "relative_path" field. It's identical to RelativePathEQ.
func RelativePath(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldRelativePath, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldMimeType, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldSize, v))
}

// Width applies equality check predicate on the "width" field. It's identical to WidthEQ.
func Width(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldWidth, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldHeight, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtContains applies the Contains predicate on the "created_at" field.
func CreatedAtContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldCreatedAt, v))
}

// CreatedAtHasPrefix applies the HasPrefix predicate on the "created_at" field.
func CreatedAtHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldCreatedAt, v))
}

// CreatedAtHasSuffix applies the HasSuffix predicate on the "created_at" field.
func CreatedAtHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldCreatedAt, v))
}

// CreatedAtEqualFold applies the EqualFold predicate on the "created_at" field.
func CreatedAtEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldCreatedAt, v))
}

// CreatedAtContainsFold applies the ContainsFold predicate on the "created_at" field.
func CreatedAtContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtContains applies the Contains predicate on the "updated_at" field.
func UpdatedAtContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldUpdatedAt, v))
}

// UpdatedAtHasPrefix applies the HasPrefix predicate on the "updated_at" field.
func UpdatedAtHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldUpdatedAt, v))
}

// UpdatedAtHasSuffix applies the HasSuffix predicate on the "updated_at" field.
func UpdatedAtHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldUpdatedAt, v))
}

// UpdatedAtEqualFold applies the EqualFold predicate on the "updated_at" field.
func UpdatedAtEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldUpdatedAt, v))
}

// UpdatedAtContainsFold applies the ContainsFold predicate on the "updated_at" field.
func UpdatedAtContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtContains applies the Contains predicate on the "deleted_at" field.
func DeletedAtContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldDeletedAt, v))
}

// DeletedAtHasPrefix applies the HasPrefix predicate on the "deleted_at" field.
func DeletedAtHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldDeletedAt, v))
}

// DeletedAtHasSuffix applies the HasSuffix predicate on the "deleted_at" field.
func DeletedAtHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotNull(FieldDeletedAt))
}

// DeletedAtEqualFold applies the EqualFold predicate on the "deleted_at" field.
func DeletedAtEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldDeletedAt, v))
}

// DeletedAtContainsFold applies the ContainsFold predicate on the "deleted_at" field.
func DeletedAtContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldDeletedAt, v))
}

// UUIDEQ applies the EQ predicate on the "uuid" field.
func UUIDEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldUUID, v))
}

// UUIDNEQ applies the NEQ predicate on the "uuid" field.
func UUIDNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldUUID, v))
}

// UUIDIn applies the In predicate on the "uuid" field.
func UUIDIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldUUID, vs...))
}

// UUIDNotIn applies the NotIn predicate on the "uuid" field.
func UUIDNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldUUID, vs...))
}

// UUIDGT applies the GT predicate on the "uuid" field.
func UUIDGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldUUID, v))
}

// UUIDGTE applies the GTE predicate on the "uuid" field.
func UUIDGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldUUID, v))
}

// UUIDLT applies the LT predicate on the "uuid" field.
func UUIDLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldUUID, v))
}

// UUIDLTE applies the LTE predicate on the "uuid" field.
func UUIDLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldUUID, v))
}

// UUIDContains applies the Contains predicate on the "uuid" field.
func UUIDContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldUUID, v))
}

// UUIDHasPrefix applies the HasPrefix predicate on the "uuid" field.
func UUIDHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldUUID, v))
}

// UUIDHasSuffix applies the HasSuffix predicate on the "uuid" field.
func UUIDHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldUUID, v))
}

// UUIDEqualFold applies the EqualFold predicate on the "uuid" field.
func UUIDEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldUUID, v))
}

// UUIDContainsFold applies the ContainsFold predicate on the "uuid" field.
func UUIDContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldUUID, v))
}

// AssetIDEQ applies the EQ predicate on the "asset_id" field.
func AssetIDEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldAssetID, v))
}

// AssetIDNEQ applies the NEQ predicate on the "asset_id" field.
func AssetIDNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldAssetID, v))
}

// AssetIDIn applies the In predicate on the "asset_id" field.
func AssetIDIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldAssetID, vs...))
}

// AssetIDNotIn applies the NotIn predicate on the "asset_id" field.
func AssetIDNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldAssetID, vs...))
}

// AssetIDGT applies the GT predicate on the "asset_id" field.
func AssetIDGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldAssetID, v))
}

// AssetIDGTE applies the GTE predicate on the "asset_id" field.
func AssetIDGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldAssetID, v))
}

// AssetIDLT applies the LT predicate on the "asset_id" field.
func AssetIDLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldAssetID, v))
}

// AssetIDLTE applies the LTE predicate on the "asset_id" field.
func AssetIDLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldAssetID, v))
}

// AssetIDContains applies the Contains predicate on the "asset_id" field.
func AssetIDContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldAssetID, v))
}

// AssetIDHasPrefix applies the HasPrefix predicate on the "asset_id" field.
func AssetIDHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldAssetID, v))
}

// AssetIDHasSuffix applies the HasSuffix predicate on the "asset_id" field.
func AssetIDHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldAssetID, v))
}

// AssetIDEqualFold applies the EqualFold predicate on the "asset_id" field.
func AssetIDEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldAssetID, v))
}

// AssetIDContainsFold applies the ContainsFold predicate on the "asset_id" field.
func AssetIDContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldAssetID, v))
}

// OriginalFilenameEQ applies the EQ predicate on the "original_filename" field.
func OriginalFilenameEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldOriginalFilename, v))
}

// OriginalFilenameNEQ applies the NEQ predicate on the "original_filename" field.
func OriginalFilenameNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldOriginalFilename, v))
}

// OriginalFilenameIn applies the In predicate on the "original_filename" field.
func OriginalFilenameIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldOriginalFilename, vs...))
}

// OriginalFilenameNotIn applies the NotIn predicate on the "original_filename" field.
func OriginalFilenameNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldOriginalFilename, vs...))
}

// OriginalFilenameGT applies the GT predicate on the "original_filename" field.
func OriginalFilenameGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldOriginalFilename, v))
}

// OriginalFilenameGTE applies the GTE predicate on the "original_filename" field.
func OriginalFilenameGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldOriginalFilename, v))
}

// OriginalFilenameLT applies the LT predicate on the "original_filename" field.
func OriginalFilenameLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldOriginalFilename, v))
}

// OriginalFilenameLTE applies the LTE predicate on the "original_filename" field.
func OriginalFilenameLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldOriginalFilename, v))
}

// OriginalFilenameContains applies the Contains predicate on the "original_filename" field.
func OriginalFilenameContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldOriginalFilename, v))
}

// OriginalFilenameHasPrefix applies the HasPrefix predicate on the "original_filename" field.
func OriginalFilenameHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldOriginalFilename, v))
}

// OriginalFilenameHasSuffix applies the HasSuffix predicate on the "original_filename" field.
func OriginalFilenameHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldOriginalFilename, v))
}

// OriginalFilenameIsNil applies the IsNil predicate on the "original_filename" field.
func OriginalFilenameIsNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIsNull(FieldOriginalFilename))
}

// OriginalFilenameNotNil applies the NotNil predicate on the "original_filename" field.
func OriginalFilenameNotNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotNull(FieldOriginalFilename))
}

// OriginalFilenameEqualFold applies the EqualFold predicate on the "original_filename" field.
func OriginalFilenameEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldOriginalFilename, v))
}

// OriginalFilenameContainsFold applies the ContainsFold predicate on the "original_filename" field.
func OriginalFilenameContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldOriginalFilename, v))
}

// RelativePathEQ applies the EQ predicate on the "relative_path" field.
func RelativePathEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldRelativePath, v))
}

// RelativePathNEQ applies the NEQ predicate on the "relative_path" field.
func RelativePathNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldRelativePath, v))
}

// RelativePathIn applies the In predicate on the "relative_path" field.
func RelativePathIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldRelativePath, vs...))
}

// RelativePathNotIn applies the NotIn predicate on the "relative_path" field.
func RelativePathNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldRelativePath, vs...))
}

// RelativePathGT applies the GT predicate on the "relative_path" field.
func RelativePathGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldRelativePath, v))
}

// RelativePathGTE applies the GTE predicate on the "relative_path" field.
func RelativePathGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldRelativePath, v))
}

// RelativePathLT applies the LT predicate on the "relative_path" field.
func RelativePathLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldRelativePath, v))
}

// RelativePathLTE applies the LTE predicate on the "relative_path" field.
func RelativePathLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldRelativePath, v))
}

// RelativePathContains applies the Contains predicate on the "relative_path" field.
func RelativePathContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldRelativePath, v))
}

// RelativePathHasPrefix applies the HasPrefix predicate on the "relative_path" field.
func RelativePathHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldRelativePath, v))
}

// RelativePathHasSuffix applies the HasSuffix predicate on the "relative_path" field.
func RelativePathHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldRelativePath, v))
}

// RelativePathEqualFold applies the EqualFold predicate on the "relative_path" field.
func RelativePathEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldRelativePath, v))
}

// RelativePathContainsFold applies the ContainsFold predicate on the "relative_path" field.
func RelativePathContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldRelativePath, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldMimeType, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldSize, v))
}

// WidthEQ applies the EQ predicate on the "width" field.
func WidthEQ(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldWidth, v))
}

// WidthNEQ applies the NEQ predicate on the "width" field.
func WidthNEQ(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldWidth, v))
}

// WidthIn applies the In predicate on the "width" field.
func WidthIn(vs ...int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldWidth, vs...))
}

// WidthNotIn applies the NotIn predicate on the "width" field.
func WidthNotIn(vs ...int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldWidth, vs...))
}

// WidthGT applies the GT predicate on the "width" field.
func WidthGT(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldWidth, v))
}

// WidthGTE applies the GTE predicate on the "width" field.
func WidthGTE(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldWidth, v))
}

// WidthLT applies the LT predicate on the "width" field.
func WidthLT(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldWidth, v))
}

// WidthLTE applies the LTE predicate on the "width" field.
func WidthLTE(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldWidth, v))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldHeight, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MediaAsset) predicate.MediaAsset {
	return predicate.MediaAsset(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MediaAsset) predicate.MediaAsset {
	return predicate.MediaAsset(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MediaAsset) predicate.MediaAsset {
	return predicate.MediaAsset(sql.NotPredicates(p))
}
