import {Extension} from '@codemirror/state';
import {createBaseTheme} from '../base';
import type {ThemeColors} from '../types';

export const config: ThemeColors = {
  themeName: 'aura',
  dark: true,

  background: '#21202e',
  backgroundSecondary: '#2b2a3b',

  foreground: '#edecee',
  cursor: '#a277ff',
  selection: '#3d375e7f',
  activeLine: '#4d4b6622',
  lineNumber: '#a394f033',
  activeLineNumber: '#cdccce',
  diffInserted: '#61ffca',
  diffDeleted: '#ff6767',
  diffChanged: '#ffca85',
  borderColor: '#3b334b',
  matchingBracket: '#a394f033',

  comment: '#6d6d6d',
  lineComment: '#5c5c5c',
  blockComment: '#5a5a5a',
  docComment: '#747474',
  name: '#edecee',
  variableName: '#edecee',
  typeName: '#82e2ff',
  tagName: '#7cd4ff',
  propertyName: '#d2d1f9',
  attributeName: '#f6d1ff',
  className: '#95dbff',
  labelName: '#ffc285',
  namespace: '#6fd0ff',
  macroName: '#ffca85',
  literal: '#82e2ff',
  string: '#61ffca',
  docString: '#61ffca',
  character: '#73ffd7',
  attributeValue: '#ffe3c4',
  number: '#82e2ff',
  integer: '#82e2ff',
  float: '#82e2ff',
  bool: '#ffd18b',
  regexp: '#61ffca',
  escape: '#4ff7c6',
  color: '#ffc57c',
  url: '#7cd4ff',
  keyword: '#a277ff',
  self: '#c89eff',
  null: '#f69aff',
  atom: '#61ffca',
  unit: '#61ffca',
  modifier: '#c094ff',
  operatorKeyword: '#b98dff',
  controlKeyword: '#c17aff',
  definitionKeyword: '#bd8eff',
  moduleKeyword: '#cfa2ff',
  operator: '#a277ff',
  derefOperator: '#c59bff',
  arithmeticOperator: '#c78df5',
  logicOperator: '#c088ff',
  bitwiseOperator: '#ce8cff',
  compareOperator: '#c786ff',
  updateOperator: '#bb7cff',
  definitionOperator: '#b070ff',
  typeOperator: '#b98aff',
  controlOperator: '#a867ff',
  punctuation: '#d1a6ff',
  separator: '#ceb1ff',
  bracket: '#adabff',
  angleBracket: '#ffc3ff',
  squareBracket: '#ff9ddd',
  paren: '#f39ddf',
  brace: '#f589d6',
  content: '#edecee',
  heading: '#a277ff',
  heading1: '#caa0ff',
  heading2: '#c192ff',
  heading3: '#b684ff',
  heading4: '#aa76ff',
  heading5: '#9f68ff',
  heading6: '#955aff',
  contentSeparator: '#a277ff',
  list: '#c0c0c0',
  quote: '#9280a3',
  emphasis: '#edecee',
  strong: '#f4f3f5',
  link: '#79d3ff',
  monospace: '#d5d0d8',
  strikethrough: '#b9b3c0',
  inserted: '#61ffca',
  deleted: '#ff6767',
  changed: '#ffca85',
  invalid: '#ff6767',
  meta: '#807d8c',
  documentMeta: '#7b7886',
  annotation: '#7df5d9',
  processingInstruction: '#7b7490',
  definition: '#d0cfe4',
  constant: '#61ffca',
  function: '#ffca85',
  standard: '#c1c0cf',
  local: '#c9c8d7',
  special: '#ffd9a8',
};

export const aura: Extension = createBaseTheme(config);
