// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  preDiagramLine = 11,
  PieDiagram = 1,
  MindmapDiagram = 2,
  FlowchartDiagram = 3,
  SequenceDiagram = 4,
  JourneyDiagram = 5,
  RequirementDiagram = 6,
  GanttDiagram = 7,
  MermaidDiagram = 8
