// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"voidraft/internal/models"
	"voidraft/internal/models/ent/predicate"
	"voidraft/internal/models/ent/syncrunlog"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SyncRunLogUpdate is the builder for updating SyncRunLog entities.
type SyncRunLogUpdate struct {
	config
	hooks     []Hook
	mutation  *SyncRunLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SyncRunLogUpdate builder.
func (_u *SyncRunLogUpdate) Where(ps ...predicate.SyncRunLog) *SyncRunLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *SyncRunLogUpdate) SetTargetType(v syncrunlog.TargetType) *SyncRunLogUpdate {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *SyncRunLogUpdate) SetNillableTargetType(v *syncrunlog.TargetType) *SyncRunLogUpdate {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetTargetPath sets the "target_path" field.
func (_u *SyncRunLogUpdate) SetTargetPath(v string) *SyncRunLogUpdate {
	_u.mutation.SetTargetPath(v)
	return _u
}

// SetNillableTargetPath sets the "target_path" field if the given value is not nil.
func (_u *SyncRunLogUpdate) SetNillableTargetPath(v *string) *SyncRunLogUpdate {
	if v != nil {
		_u.SetTargetPath(*v)
	}
	return _u
}

// SetBranch sets the "branch" field.
func (_u *SyncRunLogUpdate) SetBranch(v string) *SyncRunLogUpdate {
	_u.mutation.SetBranch(v)
	return _u
}

// SetNillableBranch sets the "branch" field if the given value is not nil.
func (_u *SyncRunLogUpdate) SetNillableBranch(v *string) *SyncRunLogUpdate {
	if v != nil {
		_u.SetBranch(*v)
	}
	return _u
}

// SetTriggerType sets the "trigger_type" field.
func (_u *SyncRunLogUpdate) SetTriggerType(v syncrunlog.TriggerType) *SyncRunLogUpdate {
	_u.mutation.SetTriggerType(v)
	return _u
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (_u *SyncRunLogUpdate) SetNillableTriggerType(v *syncrunlog.TriggerType) *SyncRunLogUpdate {
	if v != nil {
		_u.SetTriggerType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SyncRunLogUpdate) SetStatus(v syncrunlog.Status) *SyncRunLogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SyncRunLogUpdate) SetNillableStatus(v *syncrunlog.Status) *SyncRunLogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *SyncRunLogUpdate) SetStartedAt(v string) *SyncRunLogUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *SyncRunLogUpdate) SetNillableStartedAt(v *string) *SyncRunLogUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *SyncRunLogUpdate) SetFinishedAt(v string) *SyncRunLogUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *SyncRunLogUpdate) SetNillableFinishedAt(v *string) *SyncRunLogUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// SetDetails sets the "details" field.
func (_u *SyncRunLogUpdate) SetDetails(v models.SyncRunDetails) *SyncRunLogUpdate {
	_u.mutation.SetDetails(v)
	return _u
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (_u *SyncRunLogUpdate) SetNillableDetails(v *models.SyncRunDetails) *SyncRunLogUpdate {
	if v != nil {
		_u.SetDetails(*v)
	}
	return _u
}

// Mutation returns the SyncRunLogMutation object of the builder.
func (_u *SyncRunLogUpdate) Mutation() *SyncRunLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SyncRunLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncRunLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SyncRunLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncRunLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SyncRunLogUpdate) check() error {
	if v, ok := _u.mutation.TargetType(); ok {
		if err := syncrunlog.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "SyncRunLog.target_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerType(); ok {
		if err := syncrunlog.TriggerTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_type", err: fmt.Errorf(`ent: validator failed for field "SyncRunLog.trigger_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := syncrunlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SyncRunLog.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SyncRunLogUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SyncRunLogUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SyncRunLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(syncrunlog.Table, syncrunlog.Columns, sqlgraph.NewFieldSpec(syncrunlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(syncrunlog.FieldTargetType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TargetPath(); ok {
		_spec.SetField(syncrunlog.FieldTargetPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Branch(); ok {
		_spec.SetField(syncrunlog.FieldBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerType(); ok {
		_spec.SetField(syncrunlog.FieldTriggerType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(syncrunlog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(syncrunlog.FieldStartedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(syncrunlog.FieldFinishedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(syncrunlog.FieldDetails, field.TypeJSON, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncrunlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SyncRunLogUpdateOne is the builder for updating a single SyncRunLog entity.
type SyncRunLogUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SyncRunLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTargetType sets the "target_type" field.
func (_u *SyncRunLogUpdateOne) SetTargetType(v syncrunlog.TargetType) *SyncRunLogUpdateOne {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *SyncRunLogUpdateOne) SetNillableTargetType(v *syncrunlog.TargetType) *SyncRunLogUpdateOne {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetTargetPath sets the "target_path" field.
func (_u *SyncRunLogUpdateOne) SetTargetPath(v string) *SyncRunLogUpdateOne {
	_u.mutation.SetTargetPath(v)
	return _u
}

// SetNillableTargetPath sets the "target_path" field if the given value is not nil.
func (_u *SyncRunLogUpdateOne) SetNillableTargetPath(v *string) *SyncRunLogUpdateOne {
	if v != nil {
		_u.SetTargetPath(*v)
	}
	return _u
}

// SetBranch sets the "branch" field.
func (_u *SyncRunLogUpdateOne) SetBranch(v string) *SyncRunLogUpdateOne {
	_u.mutation.SetBranch(v)
	return _u
}

// SetNillableBranch sets the "branch" field if the given value is not nil.
func (_u *SyncRunLogUpdateOne) SetNillableBranch(v *string) *SyncRunLogUpdateOne {
	if v != nil {
		_u.SetBranch(*v)
	}
	return _u
}

// SetTriggerType sets the "trigger_type" field.
func (_u *SyncRunLogUpdateOne) SetTriggerType(v syncrunlog.TriggerType) *SyncRunLogUpdateOne {
	_u.mutation.SetTriggerType(v)
	return _u
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (_u *SyncRunLogUpdateOne) SetNillableTriggerType(v *syncrunlog.TriggerType) *SyncRunLogUpdateOne {
	if v != nil {
		_u.SetTriggerType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SyncRunLogUpdateOne) SetStatus(v syncrunlog.Status) *SyncRunLogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SyncRunLogUpdateOne) SetNillableStatus(v *syncrunlog.Status) *SyncRunLogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *SyncRunLogUpdateOne) SetStartedAt(v string) *SyncRunLogUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *SyncRunLogUpdateOne) SetNillableStartedAt(v *string) *SyncRunLogUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *SyncRunLogUpdateOne) SetFinishedAt(v string) *SyncRunLogUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *SyncRunLogUpdateOne) SetNillableFinishedAt(v *string) *SyncRunLogUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// SetDetails sets the "details" field.
func (_u *SyncRunLogUpdateOne) SetDetails(v models.SyncRunDetails) *SyncRunLogUpdateOne {
	_u.mutation.SetDetails(v)
	return _u
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (_u *SyncRunLogUpdateOne) SetNillableDetails(v *models.SyncRunDetails) *SyncRunLogUpdateOne {
	if v != nil {
		_u.SetDetails(*v)
	}
	return _u
}

// Mutation returns the SyncRunLogMutation object of the builder.
func (_u *SyncRunLogUpdateOne) Mutation() *SyncRunLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the SyncRunLogUpdate builder.
func (_u *SyncRunLogUpdateOne) Where(ps ...predicate.SyncRunLog) *SyncRunLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SyncRunLogUpdateOne) Select(field string, fields ...string) *SyncRunLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SyncRunLog entity.
func (_u *SyncRunLogUpdateOne) Save(ctx context.Context) (*SyncRunLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncRunLogUpdateOne) SaveX(ctx context.Context) *SyncRunLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SyncRunLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncRunLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SyncRunLogUpdateOne) check() error {
	if v, ok := _u.mutation.TargetType(); ok {
		if err := syncrunlog.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "SyncRunLog.target_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerType(); ok {
		if err := syncrunlog.TriggerTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_type", err: fmt.Errorf(`ent: validator failed for field "SyncRunLog.trigger_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := syncrunlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SyncRunLog.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SyncRunLogUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SyncRunLogUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SyncRunLogUpdateOne) sqlSave(ctx context.Context) (_node *SyncRunLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(syncrunlog.Table, syncrunlog.Columns, sqlgraph.NewFieldSpec(syncrunlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SyncRunLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, syncrunlog.FieldID)
		for _, f := range fields {
			if !syncrunlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != syncrunlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(syncrunlog.FieldTargetType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TargetPath(); ok {
		_spec.SetField(syncrunlog.FieldTargetPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Branch(); ok {
		_spec.SetField(syncrunlog.FieldBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerType(); ok {
		_spec.SetField(syncrunlog.FieldTriggerType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(syncrunlog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(syncrunlog.FieldStartedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(syncrunlog.FieldFinishedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(syncrunlog.FieldDetails, field.TypeJSON, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &SyncRunLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncrunlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
