// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"voidraft/internal/models"
	"voidraft/internal/models/ent/syncrunlog"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SyncRunLog is the model entity for the SyncRunLog schema.
type SyncRunLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// sync target type
	TargetType syncrunlog.TargetType `json:"target_type"`
	// git repo url or localfs root path
	TargetPath string `json:"target_path"`
	// configured sync branch
	Branch string `json:"branch"`
	// sync trigger type
	TriggerType syncrunlog.TriggerType `json:"trigger_type"`
	// sync result status
	Status syncrunlog.Status `json:"status"`
	// sync start time
	StartedAt string `json:"started_at"`
	// sync finish time
	FinishedAt string `json:"finished_at"`
	// sync run details
	Details      models.SyncRunDetails `json:"details"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SyncRunLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case syncrunlog.FieldDetails:
			values[i] = new([]byte)
		case syncrunlog.FieldID:
			values[i] = new(sql.NullInt64)
		case syncrunlog.FieldTargetType, syncrunlog.FieldTargetPath, syncrunlog.FieldBranch, syncrunlog.FieldTriggerType, syncrunlog.FieldStatus, syncrunlog.FieldStartedAt, syncrunlog.FieldFinishedAt:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SyncRunLog fields.
func (_m *SyncRunLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case syncrunlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case syncrunlog.FieldTargetType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_type", values[i])
			} else if value.Valid {
				_m.TargetType = syncrunlog.TargetType(value.String)
			}
		case syncrunlog.FieldTargetPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_path", values[i])
			} else if value.Valid {
				_m.TargetPath = value.String
			}
		case syncrunlog.FieldBranch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field branch", values[i])
			} else if value.Valid {
				_m.Branch = value.String
			}
		case syncrunlog.FieldTriggerType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_type", values[i])
			} else if value.Valid {
				_m.TriggerType = syncrunlog.TriggerType(value.String)
			}
		case syncrunlog.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = syncrunlog.Status(value.String)
			}
		case syncrunlog.FieldStartedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.String
			}
		case syncrunlog.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = value.String
			}
		case syncrunlog.FieldDetails:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field details", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Details); err != nil {
					return fmt.Errorf("unmarshal field details: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SyncRunLog.
// This includes values selected through modifiers, order, etc.
func (_m *SyncRunLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SyncRunLog.
// Note that you need to call SyncRunLog.Unwrap() before calling this method if this SyncRunLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SyncRunLog) Update() *SyncRunLogUpdateOne {
	return NewSyncRunLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SyncRunLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SyncRunLog) Unwrap() *SyncRunLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SyncRunLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SyncRunLog) String() string {
	var builder strings.Builder
	builder.WriteString("SyncRunLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("target_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetType))
	builder.WriteString(", ")
	builder.WriteString("target_path=")
	builder.WriteString(_m.TargetPath)
	builder.WriteString(", ")
	builder.WriteString("branch=")
	builder.WriteString(_m.Branch)
	builder.WriteString(", ")
	builder.WriteString("trigger_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.TriggerType))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt)
	builder.WriteString(", ")
	builder.WriteString("finished_at=")
	builder.WriteString(_m.FinishedAt)
	builder.WriteString(", ")
	builder.WriteString("details=")
	builder.WriteString(fmt.Sprintf("%v", _m.Details))
	builder.WriteByte(')')
	return builder.String()
}

// SyncRunLogs is a parsable slice of SyncRunLog.
type SyncRunLogs []*SyncRunLog
