// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DocumentsColumns holds the columns for the "documents" table.
	DocumentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uuid", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeString},
		{Name: "deleted_at", Type: field.TypeString, Nullable: true},
		{Name: "title", Type: field.TypeString, Size: 255},
		{Name: "content", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: "\n∞∞∞text-a-w\n"},
		{Name: "locked", Type: field.TypeBool, Default: false},
	}
	// DocumentsTable holds the schema information for the "documents" table.
	DocumentsTable = &schema.Table{
		Name:       "documents",
		Columns:    DocumentsColumns,
		PrimaryKey: []*schema.Column{DocumentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "document_uuid",
				Unique:  false,
				Columns: []*schema.Column{DocumentsColumns[1]},
			},
			{
				Name:    "document_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{DocumentsColumns[4]},
			},
			{
				Name:    "document_title",
				Unique:  false,
				Columns: []*schema.Column{DocumentsColumns[5]},
			},
			{
				Name:    "document_created_at",
				Unique:  false,
				Columns: []*schema.Column{DocumentsColumns[2]},
			},
			{
				Name:    "document_updated_at",
				Unique:  false,
				Columns: []*schema.Column{DocumentsColumns[3]},
			},
		},
	}
	// ExtensionsColumns holds the columns for the "extensions" table.
	ExtensionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uuid", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeString},
		{Name: "deleted_at", Type: field.TypeString, Nullable: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "config", Type: field.TypeJSON, Nullable: true},
	}
	// ExtensionsTable holds the schema information for the "extensions" table.
	ExtensionsTable = &schema.Table{
		Name:       "extensions",
		Columns:    ExtensionsColumns,
		PrimaryKey: []*schema.Column{ExtensionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "extension_uuid",
				Unique:  false,
				Columns: []*schema.Column{ExtensionsColumns[1]},
			},
			{
				Name:    "extension_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{ExtensionsColumns[4]},
			},
			{
				Name:    "extension_enabled",
				Unique:  false,
				Columns: []*schema.Column{ExtensionsColumns[6]},
			},
		},
	}
	// KeyBindingsColumns holds the columns for the "key_bindings" table.
	KeyBindingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uuid", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeString},
		{Name: "deleted_at", Type: field.TypeString, Nullable: true},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "type", Type: field.TypeString, Size: 20, Default: "standard"},
		{Name: "key", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "macos", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "windows", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "linux", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "extension", Type: field.TypeString, Size: 100},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "prevent_default", Type: field.TypeBool, Default: true},
		{Name: "scope", Type: field.TypeString, Size: 100, Default: "editor"},
	}
	// KeyBindingsTable holds the schema information for the "key_bindings" table.
	KeyBindingsTable = &schema.Table{
		Name:       "key_bindings",
		Columns:    KeyBindingsColumns,
		PrimaryKey: []*schema.Column{KeyBindingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "keybinding_uuid",
				Unique:  false,
				Columns: []*schema.Column{KeyBindingsColumns[1]},
			},
			{
				Name:    "keybinding_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{KeyBindingsColumns[4]},
			},
			{
				Name:    "keybinding_name",
				Unique:  false,
				Columns: []*schema.Column{KeyBindingsColumns[5]},
			},
			{
				Name:    "keybinding_type",
				Unique:  false,
				Columns: []*schema.Column{KeyBindingsColumns[6]},
			},
			{
				Name:    "keybinding_type_name",
				Unique:  true,
				Columns: []*schema.Column{KeyBindingsColumns[6], KeyBindingsColumns[5]},
			},
			{
				Name:    "keybinding_extension",
				Unique:  false,
				Columns: []*schema.Column{KeyBindingsColumns[11]},
			},
			{
				Name:    "keybinding_enabled",
				Unique:  false,
				Columns: []*schema.Column{KeyBindingsColumns[12]},
			},
		},
	}
	// MediaAssetsColumns holds the columns for the "media_assets" table.
	MediaAssetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeString},
		{Name: "uuid", Type: field.TypeString, Unique: true},
		{Name: "asset_id", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "filename", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "path", Type: field.TypeString, Unique: true, Size: 1024},
		{Name: "mime_type", Type: field.TypeString, Size: 128},
		{Name: "size", Type: field.TypeInt64},
		{Name: "width", Type: field.TypeInt},
		{Name: "height", Type: field.TypeInt},
	}
	// MediaAssetsTable holds the schema information for the "media_assets" table.
	MediaAssetsTable = &schema.Table{
		Name:       "media_assets",
		Columns:    MediaAssetsColumns,
		PrimaryKey: []*schema.Column{MediaAssetsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "mediaasset_uuid",
				Unique:  false,
				Columns: []*schema.Column{MediaAssetsColumns[3]},
			},
			{
				Name:    "mediaasset_asset_id",
				Unique:  false,
				Columns: []*schema.Column{MediaAssetsColumns[4]},
			},
			{
				Name:    "mediaasset_path",
				Unique:  false,
				Columns: []*schema.Column{MediaAssetsColumns[6]},
			},
			{
				Name:    "mediaasset_created_at",
				Unique:  false,
				Columns: []*schema.Column{MediaAssetsColumns[1]},
			},
			{
				Name:    "mediaasset_updated_at",
				Unique:  false,
				Columns: []*schema.Column{MediaAssetsColumns[2]},
			},
		},
	}
	// SyncRunLogsColumns holds the columns for the "sync_run_logs" table.
	SyncRunLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "target_type", Type: field.TypeEnum, Enums: []string{"git", "localfs"}},
		{Name: "target_path", Type: field.TypeString, Default: ""},
		{Name: "branch", Type: field.TypeString, Default: ""},
		{Name: "trigger_type", Type: field.TypeEnum, Enums: []string{"manual", "auto"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"success", "failed"}},
		{Name: "started_at", Type: field.TypeString},
		{Name: "finished_at", Type: field.TypeString},
		{Name: "details", Type: field.TypeJSON},
	}
	// SyncRunLogsTable holds the schema information for the "sync_run_logs" table.
	SyncRunLogsTable = &schema.Table{
		Name:       "sync_run_logs",
		Columns:    SyncRunLogsColumns,
		PrimaryKey: []*schema.Column{SyncRunLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "syncrunlog_started_at",
				Unique:  false,
				Columns: []*schema.Column{SyncRunLogsColumns[6]},
			},
			{
				Name:    "syncrunlog_status_started_at",
				Unique:  false,
				Columns: []*schema.Column{SyncRunLogsColumns[5], SyncRunLogsColumns[6]},
			},
			{
				Name:    "syncrunlog_target_type_started_at",
				Unique:  false,
				Columns: []*schema.Column{SyncRunLogsColumns[1], SyncRunLogsColumns[6]},
			},
			{
				Name:    "syncrunlog_trigger_type_started_at",
				Unique:  false,
				Columns: []*schema.Column{SyncRunLogsColumns[4], SyncRunLogsColumns[6]},
			},
		},
	}
	// ThemesColumns holds the columns for the "themes" table.
	ThemesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uuid", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeString},
		{Name: "deleted_at", Type: field.TypeString, Nullable: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"dark", "light"}},
		{Name: "colors", Type: field.TypeJSON, Nullable: true},
	}
	// ThemesTable holds the schema information for the "themes" table.
	ThemesTable = &schema.Table{
		Name:       "themes",
		Columns:    ThemesColumns,
		PrimaryKey: []*schema.Column{ThemesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "theme_uuid",
				Unique:  false,
				Columns: []*schema.Column{ThemesColumns[1]},
			},
			{
				Name:    "theme_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{ThemesColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DocumentsTable,
		ExtensionsTable,
		KeyBindingsTable,
		MediaAssetsTable,
		SyncRunLogsTable,
		ThemesTable,
	}
)

func init() {
	DocumentsTable.Annotation = &entsql.Annotation{
		Table: "documents",
	}
	ExtensionsTable.Annotation = &entsql.Annotation{
		Table: "extensions",
	}
	KeyBindingsTable.Annotation = &entsql.Annotation{
		Table: "key_bindings",
	}
	MediaAssetsTable.Annotation = &entsql.Annotation{
		Table: "media_assets",
	}
	SyncRunLogsTable.Annotation = &entsql.Annotation{
		Table: "sync_run_logs",
	}
	ThemesTable.Annotation = &entsql.Annotation{
		Table: "themes",
	}
}
